//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;

namespace RTPuzzle
{
    public class NearPlayerGameOverTriggerModule : RTPuzzle.InteractiveObjectModule
    {
        public PuzzleCutsceneGraph TestGraph;

        #region External Dependencies
        private AISightVision AISightVision;
        private BlockingCutscenePlayer BlockingCutscenePlayer;
        private PuzzleEventsManager PuzzleEventsManager;
        #endregion
        private InteractiveObjectType InteractiveObjectTypeRef;

        public void Init(AISightVision AISightVision, InteractiveObjectType InteractiveObjectTypeRef)
        {
            this.AISightVision = AISightVision;
            this.BlockingCutscenePlayer = GameObject.FindObjectOfType<BlockingCutscenePlayer>();
            this.PuzzleEventsManager = GameObject.FindObjectOfType<PuzzleEventsManager>();

            this.InteractiveObjectTypeRef = InteractiveObjectTypeRef;
        }

        private void OnTriggerEnter(Collider other)
        {
            var collisionType = other.GetComponent<CollisionType>();
            if ((collisionType != null && collisionType.IsPlayer) &&
                ((this.AISightVision == null) || (this.AISightVision != null && this.AISightVision.IsPlayerInSight())))
            {
                this.BlockingCutscenePlayer.Play(new PuzzleCutsceneActionInput(GameObject.FindObjectOfType<InteractiveObjectContainer>(), new System.Collections.Generic.Dictionary<PuzzleCutsceneParametersName, object>() {
                    {PuzzleCutsceneParametersName.INTERACTIVE_OBJECT_0, this.InteractiveObjectTypeRef }
                }), this.TestGraph, onCutsceneEnd: () =>
                {
                    this.PuzzleEventsManager.PZ_EVT_LevelReseted();
                });
            }
        }
    }
}
