//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CoreGame;
using UnityEngine;

namespace RTPuzzle
{


    public class InteractiveObjectInitializationObject
    {

        public RTPuzzle.AttractiveObjectInherentConfigurationData InputAttractiveObjectInherentConfigurationData;

        public RTPuzzle.TargetZoneInherentData TargetZoneInherentData;

        public RTPuzzle.LaunchProjectileInherentData LaunchProjectileInherentData;

        public RTPuzzle.DisarmObjectInherentData DisarmObjectInherentData;

        public CoreGame.BeziersControlPoints ProjectilePath;

        public RTPuzzle.ActionInteractableObjectInherentData ActionInteractableObjectInherentData;

        public RTPuzzle.GrabObjectInherentData GrabObjectInherentData;

        public TransformMoveManagerComponentV2 TransformMoveManagerComponent;

        public Rigidbody RigidBody;
        
    }
}
