//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor_MainGameCreationWizard
{
    
    
    public class NameConstants
    {
        
        public static string BaseLevelChunkPrefab = "_BaseLevelPrefab";
        
        public static string LevelCompletionConditionConfigurationName = "_LevelCompletionCondition";
        
        public static string LevelCompletionInherentData = "_LevelCompletionInherentData";
        
        public static string LevelConfigurationData = "_LevelConfigurationData";
        
        public static string PuzzleLevelDynamics = "_PuzzleLevelDynamics";
        
        public static string AdventureLevelDynamics = "_AdventureLevelDynamics";
        
        public static string LevelHierarchyConfigurationData = "_LevelHierarchyConfigurationData";
        
        public static string LevelSceneConfigurationData = "_LevelZonesSceneConfigurationData";
        
        public static string LevelChunkSceneConfigurationData = "_ChunkZonesSceneConfigurationData";
        
        public static string BaseAIPrefab = "_AIPrefab";
        
        public static string AIBehavior = "_AIBehavior";
        
        public static string AIComponents = "_AIComponents";
        
        public static string TargetZoneInherentData = "_TargetZoneInherentData";
        
        public static string TargetZonePrefab = "_TargetZone";
        
        public static string ProjectileInherentData = "_ProjectileInherentData";
        
        public static string ProjectilePrefab = "_ProjectilePrefab";
        
        public static string PlayerActionsInherentData = "_PlayerAction";
        
        public static string POIPrefab = "_POIObject";
        
        public static string POIInherentData = "_PointOfInterestInherentData";
        
        public static string AttractiveObjectPrefab = "_AttractiveObject";
        
        public static string AttractiveObjectInherentData = "_AttractiveObjectInherentData";
        
        public static string RepelableObjectInherentData = "_RepelableObjectInherentData";
        
        public static string RepelableObjectPrefab = "_RepelableObjectPrefab";
        
        public static string AnimationConfigurationdata = "_AnimationData";
        
        public static string InteractiveObject = "_Interactive";
        
        public static string DiscussionNodeEditorObject = "_NodeEditor";
        
        public static string DisarmObjectInherentData = "_DisarmObjectInherentData";
        
        public static string NearPlayerGameOverTriggerInherentData = "_NearPlayerGameOverTriggerInherentData";
        
        public static string ActionInteractableObjectInherentData = "_ActionInteractableObjectInherentData";
        
        public static string InteractiveTestInherentData = "_InteractiveTest";
        
        public static string GrabObjectInherentData = "_GrabObject";
        
        public static string CreationWizardTestInherentData = "_CreationWizardTest";
        
        public static string InteractiveObjectTypeDefinitionConfigurationInherentData = "_InteractiveObjectTypeDefinitionConfiguration";
        
        public static string InteractiveObjectTypeDefinitionInherentData = "_InteractiveObjectTypeDefinition";
        
        public static string RangeTypeObjectDefinitionInherentData = "_RangeTypeObjectDefinition";
        
        public static string AIObjectTypeDefinitionInherentData = "_AIObjectTypeDefinition";
        
        public static string PuzzleCutsceneInherentData = "_PuzzleCutscene";
        
        public static string AdventureGenerationTestInherentData = "_AdventureGenerationTest";
        
        public static string PointOfInterestDefinitionInherentData = "_PointOfInterestDefinition";
        
        public static string PointOfInterestVisualMovementInherentData = "_PointOfInterestVisualMovement";
        
        public static string PointOfInterestModuleTestInherentData = "_PointOfInterestModuleTest";
    }
}
