//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTPuzzle
{
    using UnityEngine;
    using UnityEditor;
    using OdinSerializer;
    using System;
    
    
    [Serializable()]
    [UnityEngine.CreateAssetMenu(fileName="GenericPuzzleAIComponents", menuName="Configuration/PuzzleGame/AIComponentsConfiguration/GenericPuzzleAIComponents", order=1)]
    public class GenericPuzzleAIComponents : AbstractAIComponents
    {
        
        public AIPatrolComponent AIRandomPatrolComponent;
        
        public AIProjectileEscapeComponent AIProjectileEscapeWithCollisionComponent;
        
        public AIEscapeWithoutTriggerComponent AIEscapeWithoutTriggerComponent;
        
        public AITargetZoneComponent AITargetZoneComponent;
        
        public AIAttractiveObjectComponent AIAttractiveObjectComponent;
        
        public AIFearStunComponent AIFearStunComponent;
        
        public AIPlayerEscapeComponent AIPlayerEscapeComponent;
        
        public AIMoveTowardPlayerComponent AIMoveTowardPlayerComponent;
        
        public AIDisarmObjectComponent AIDisarmObjectComponent;
    }
}
