//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using GameConfigurationID;
using System;
using System.Collections.Generic;
using UnityEngine;

namespace RTPuzzle
{

    public class VisualFeedbackEmitterModule : InteractiveObjectModule, IVisualFeedbackEmitterModuleDataRetriever
    {
        public RangeObjectV2 InRangeVisualFeedbackTrackerRange;
        private VisualFeedbackEmitterRangeIntersectionManagerV2 VisualFeedbackEmitterRangeIntersectionManagerV2;

        public override void Init(InteractiveObjectInitializationObject interactiveObjectInitializationObject, IInteractiveObjectTypeDataRetrieval IInteractiveObjectTypeDataRetrieval,
                IInteractiveObjectTypeEvents IInteractiveObjectTypeEvents)
        {
            this.VisualFeedbackEmitterRangeIntersectionManagerV2 = new VisualFeedbackEmitterRangeIntersectionManagerV2(this.InRangeVisualFeedbackTrackerRange);
            this.InRangeVisualFeedbackTrackerRange.ReceiveEvent(new RangeIntersectionAddIntersectionListenerEvent { ARangeIntersectionV2Listener = this.VisualFeedbackEmitterRangeIntersectionManagerV2 });
        }

        #region IInRangeVisualFeedbackModuleDataRetriever
        public List<ModelObjectModule> GetInRangeModelObjectsForVisual()
        {
            return this.VisualFeedbackEmitterRangeIntersectionManagerV2.InRangeModelObjectForVisual;
        }

        public RangeTypeID GetAssociatedRangeTypeID()
        {
            return this.InRangeVisualFeedbackTrackerRange.RangeObjectInitialization.RangeTypeID;
        }
        #endregion

        public override void OnInteractiveObjectDestroyed()
        {
            this.InRangeVisualFeedbackTrackerRange.OnDestroy();
        }

        public void TickAlways(float d)
        {
        }
    }

    class VisualFeedbackEmitterRangeIntersectionManagerV2 : ARangeIntersectionV2Listener
    {
        public VisualFeedbackEmitterRangeIntersectionManagerV2(RangeObjectV2 associatedRangeObject) : base(associatedRangeObject)
        {
        }

        public List<BoxCollider> InRangeCollidersForVisual { get; private set; } = new List<BoxCollider>();
        public List<ModelObjectModule> InRangeModelObjectForVisual { get; private set; } = new List<ModelObjectModule>();
        private List<Action> localListenersOnDestroy = new List<Action>();

        protected override bool ColliderSelectionGuard(RangeObjectPhysicsTriggerInfo RangeObjectPhysicsTriggerInfo)
        {
            //    return RangeObjectPhysicsTriggerInfo.OtherCollisionType.IsAI || RangeObjectPhysicsTriggerInfo.OtherCollisionType.IsRepelable;
            return false;
        }

        protected override void OnJustIntersected(RangeIntersectionCalculatorV2 intersectionCalculator)
        {
            /*
            if (intersectionCalculator.TrackedCollider.IsAI)
            {
                var IAILogicColliderModuleDataRetriever = AILogicColliderModule.AILogicColliderModuleFromCollisionType(intersectionCalculator.TrackedCollider);
                if (IAILogicColliderModuleDataRetriever != null)
                {
                    this.InRangeCollidersForVisual.Add(IAILogicColliderModuleDataRetriever.GetCollider());
                    this.InRangeModelObjectForVisual.Add(IAILogicColliderModuleDataRetriever.IInteractiveObjectTypeDataRetrieval.GetModelObjectModule());
                    this.localListenersOnDestroy.Add(null);
                }

            }
            else if (intersectionCalculator.TrackedCollider.IsRepelable)
            {
                var IObjectRepelModuleDataRetrieval = (IObjectRepelModuleDataRetrieval)ObjectRepelModule.FromCollisionType(intersectionCalculator.TrackedCollider);
                if (IObjectRepelModuleDataRetrieval != null)
                {
                    this.InRangeCollidersForVisual.Add(IObjectRepelModuleDataRetrieval.GetObjectRepelCollider());
                    this.InRangeModelObjectForVisual.Add(IObjectRepelModuleDataRetrieval.IInteractiveObjectTypeDataRetrieval.GetModelObjectModule());
                    Action destroyCallBack = null;

                    var ILineVisualFeedbackEvent = IObjectRepelModuleDataRetrieval.ILineVisualFeedbackEvent;
                    if (ILineVisualFeedbackEvent != null)
                    {
                        ILineVisualFeedbackEvent.CreateLineDirectionPositioning(DottedLineID.REPELABLE_OBJECT_FEEDBACK, this.associatedRangeObject.RangeGameObjectV2.BoundingCollider);
                        destroyCallBack = () => ILineVisualFeedbackEvent.DestroyLine(this.associatedRangeObject.RangeGameObjectV2.BoundingCollider);
                    }
                    this.localListenersOnDestroy.Add(destroyCallBack);
                }
            }
            */
        }

        protected override void OnJustNotIntersected(RangeIntersectionCalculatorV2 intersectionCalculator)
        {
            /*
            Debug.Log("VisualFeedbackEmitterRangeIntersectionManager : OnJustNotIntersected");
            if (intersectionCalculator.TrackedCollider.IsAI)
            {
                var IAILogicColliderModuleDataRetriever = AILogicColliderModule.AILogicColliderModuleFromCollisionType(intersectionCalculator.TrackedCollider);
                if (IAILogicColliderModuleDataRetriever != null)
                {
                    var index = this.InRangeCollidersForVisual.IndexOf(IAILogicColliderModuleDataRetriever.GetCollider());
                    if (index >= 0)
                    {
                        this.InRangeCollidersForVisual.RemoveAt(index);
                        this.InRangeModelObjectForVisual.RemoveAt(index);
                        this.localListenersOnDestroy.RemoveAt(index);
                    }
                }
            }
            else if (intersectionCalculator.TrackedCollider.IsRepelable)
            {
                var IObjectRepelModuleDataRetrieval = (IObjectRepelModuleDataRetrieval)ObjectRepelModule.FromCollisionType(intersectionCalculator.TrackedCollider);
                if (IObjectRepelModuleDataRetrieval != null)
                {
                    var index = this.InRangeCollidersForVisual.IndexOf(IObjectRepelModuleDataRetrieval.GetObjectRepelCollider());
                    if (index >= 0)
                    {
                        this.InRangeCollidersForVisual.RemoveAt(index);
                        this.InRangeModelObjectForVisual.RemoveAt(index);
                        this.localListenersOnDestroy.RemoveAt(index);
                    }

                    var ILineVisualFeedbackEvent = IObjectRepelModuleDataRetrieval.ILineVisualFeedbackEvent;
                    if (ILineVisualFeedbackEvent != null)
                    {
                        ILineVisualFeedbackEvent.DestroyLine(this.associatedRangeObject.RangeGameObjectV2.BoundingCollider);
                    }
                }
            }
            */
        }

        public override void OnDestroy()
        {
            for (var i = 0; i < this.InRangeCollidersForVisual.Count; i++)
            {
                if (this.localListenersOnDestroy[i] != null) { this.localListenersOnDestroy[i].Invoke(); }
            }
        }

    }
}