//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTPuzzle
{
    using GameConfigurationID;
    using UnityEngine;
    using UnityEngine.AI;

    public class AIDisarmObjectManager : AbstractAIDisarmObjectManager
    {

        private bool isDisarmingObject;

        #region External Dependencies
        private IDisarmObjectModuleDataRetrieval disarmingObject;
        private IDisarmObjectAIEventListener disarmingObjectIDisarmObjectAIEventListener;
        #endregion
        
        private AIObjectDataRetriever AIObjectDataRetriever;
        private NavMeshAgent agent;

        public AIDisarmObjectManager(AIDisarmObjectComponent associatedAIComponent) : base(associatedAIComponent)
        {
        }

        #region External Events
        public override void OnDisarmingObjectStart(IDisarmObjectModuleDataRetrieval disarmingObject)
        {
            this.disarmingObject = disarmingObject;
            //Make agent to look at object
            this.agent.transform.rotation = Quaternion.LookRotation(Vector3.ProjectOnPlane(this.disarmingObject.GetTransform().position - this.agent.transform.position, this.agent.transform.up));
            this.SetIsDisarmingObject(true);
        }

        public override void OnDisarmingObjectExit(IDisarmObjectModuleDataRetrieval disarmingObject)
        {
            if (this.disarmingObject != null && this.disarmingObject == disarmingObject)
            {
                this.disarmingObject = null;
                this.SetIsDisarmingObject(false);
            }
        }
        #endregion

        public override void Init(AIBheaviorBuildInputData AIBheaviorBuildInputData)
        {
            this.agent = AIBheaviorBuildInputData.selfAgent;
            this.AIObjectDataRetriever = AIBheaviorBuildInputData.AIObjectDataRetriever();
            this.disarmingObjectIDisarmObjectAIEventListener = AIBheaviorBuildInputData.PuzzleEventsManager;
        }

        public override void BeforeManagersUpdate(float d, float timeAttenuationFactor)
        {
        }

        public override bool IsManagerEnabled()
        {
            return (this.disarmingObject != null && this.isDisarmingObject);
        }

        public override void OnManagerTick(float d, float timeAttenuationFactor, ref NPCAIDestinationContext NPCAIDestinationContext)
        {
            //don't move while disarming
        }

        public override void OnDestinationReached()
        {
        }

        public override void OnStateReset()
        {
            this.SetIsDisarmingObject(false);
        }

        private void SetIsDisarmingObject(bool value)
        {
            if (this.isDisarmingObject && !value)
            {
                this.disarmingObjectIDisarmObjectAIEventListener.AI_EVT_DisarmObject_End(this.AIObjectDataRetriever, (IDisarmObjectModuleEvent) this.disarmingObject);
            }
            else if (!this.isDisarmingObject && value)
            {
                this.disarmingObjectIDisarmObjectAIEventListener.AI_EVT_DisarmObject_Start(this.AIObjectDataRetriever, (IDisarmObjectModuleEvent) this.disarmingObject);
            }
            this.isDisarmingObject = value;
        }
    }
}
