using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using GameConfigurationID;
using CoreGame;

namespace AdventureGame
{
    public class AdventureGameConfigurationManager : MonoBehaviour
    {
        public AdventureGameConfiguration AdventureGameConfiguration;

        public Dictionary<ItemID, ItemInherentData> ItemConf()
        {
            return AdventureGameConfiguration.ItemConfiguration.ConfigurationInherentData;
        }

        public Dictionary<CutsceneId, CutsceneInherentData> CutsceneConf()
        {
            return AdventureGameConfiguration.CutsceneConfiguration.ConfigurationInherentData;
        }
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
        public Dictionary<PointOfInterestDefinitionID, PointOfInterestDefinitionInherentData> PointOfInterestDefinitionConfiguration()
        {
            return AdventureGameConfiguration.PointOfInterestDefinitionConfiguration.ConfigurationInherentData;
        }

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------
        public Dictionary<PointOfInterestVisualMovementID, PointOfInterestVisualMovementInherentData> PointOfInterestVisualMovementConfiguration()
        {
            return AdventureGameConfiguration.PointOfInterestVisualMovementConfiguration.ConfigurationInherentData;
        }

//${addNewEntry}

        
    }

}
