//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor_GameDesigner
{
    
    
    [System.Serializable()]
    public class InteractiveObjectModuleWizardID
    {
        
        [CustomEnum(IsSearchable=true, IsCreateable=false, ChoosedOpenRepertoire=false)]
        public GameConfigurationID.ObjectRepelID ObjectRepelID;
        
        [CustomEnum(IsSearchable=true, IsCreateable=false, ChoosedOpenRepertoire=false)]
        public GameConfigurationID.AttractiveObjectId AttractiveObjectId;
        
        [CustomEnum(IsSearchable=true, IsCreateable=false, ChoosedOpenRepertoire=false)]
        public GameConfigurationID.LaunchProjectileID LaunchProjectileID;
        
        [CustomEnum(IsSearchable=true, IsCreateable=false, ChoosedOpenRepertoire=false)]
        public GameConfigurationID.TargetZoneID TargetZoneID;
        
        [CustomEnum(IsSearchable=true, IsCreateable=false, ChoosedOpenRepertoire=false)]
        public GameConfigurationID.DisarmObjectID DisarmObjectID;
        
        [CustomEnum(IsSearchable=true, IsCreateable=false, ChoosedOpenRepertoire=false)]
        public GameConfigurationID.ActionInteractableObjectID ActionInteractableObjectID;
        
        [CustomEnum(IsSearchable=true, IsCreateable=false, ChoosedOpenRepertoire=false)]
        public GameConfigurationID.GrabObjectID GrabObjectID;
    }
}
