//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using System.Collections;
using Editor_AIObjectTypeDefinitionCreationWizard;

namespace Editor_GameDesigner
{
    [System.Serializable]
    public class CreateAIObjectTypeDefinition : CreateInEditorModule<AIObjectTypeDefinitionCreationWizard>
    { 
    }
}