//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;

namespace RTPuzzle
{
    public interface IInRangeColliderTrackerModuleDataRetriever
    {
        IObjectRepelModuleDataRetrieval GetIObjectRepelModuleDataRetrieval();
    }

    public class InRangeColliderTrackerModule : InteractiveObjectModule, IInRangeColliderTrackerModuleDataRetriever, IAILogicColliderModuleListener
    {

        #region Module Dependencies
        private ModelObjectModule ModelObjectModule;
        private ObjectRepelModule ObjectRepelModule;
        #endregion

        #region External Dependencies
        private IInRangeColliderTrackerModuleEventListener IInRangeColliderTrackerModuleEventListener;
        #endregion
        
        #region IInRangeColliderTrackerModuleDataRetriever
        public IObjectRepelModuleDataRetrieval GetIObjectRepelModuleDataRetrieval() { return this.ObjectRepelModule; }
        #endregion

        public override void Init(InteractiveObjectInitializationObject interactiveObjectInitializationObject, IInteractiveObjectTypeDataRetrieval IInteractiveObjectTypeDataRetrieval,
                IInteractiveObjectTypeEvents IInteractiveObjectTypeEvents)
        {
            #region Module Dependencies
            this.ModelObjectModule = IInteractiveObjectTypeDataRetrieval.GetModelObjectModule();
            this.ObjectRepelModule = IInteractiveObjectTypeDataRetrieval.GetObjectRepelModule();
            #endregion

            IInteractiveObjectTypeDataRetrieval.GetAILogicColliderModule().AddListener(this);

            #region External Dependencies
            this.IInRangeColliderTrackerModuleEventListener = PuzzleGameSingletonInstances.RangeEventsManager;
            #endregion
        }

        public void OnAILogicColliderTriggerEnter(Collider other)
        {
            var rangeType = RangeType.RetrieveFromCollisionType(other.GetComponent<CollisionType>());
            if (rangeType != null)
            {
                this.IInRangeColliderTrackerModuleEventListener.RANGE_EVT_InsideRangeTracker(this, rangeType);
            }
        }

        public void OnAILogicColliderTriggerExit(Collider other)
        {
            var rangeType = RangeType.RetrieveFromCollisionType(other.GetComponent<CollisionType>());
            if (rangeType != null)
            {
                this.IInRangeColliderTrackerModuleEventListener.RANGE_EVT_OutsideRangeTracker(this, rangeType);
            }
        }

        public void OnAILogicColliderTriggerStay(Collider other) { }

        public void Tick(float d, float timeAttenuationFactor) { }
    }
}