//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTPuzzle
{
    using UnityEngine;
    using ConfigurationEditor;
    using GameConfigurationID;
    using System.Collections.Generic;
    
    
    [System.Serializable()]
    [UnityEngine.CreateAssetMenu(fileName="AIObjectTypeDefinitionConfiguration", menuName="Configuration/PuzzleGame/AIObjectTypeDefinitionConfiguration/AIObjectTypeDefiniti" +
        "onConfiguration", order=1)]
    public class AIObjectTypeDefinitionConfiguration : ConfigurationEditor.ConfigurationSerialization<AIObjectTypeDefinitionID, AIObjectTypeDefinitionInherentData>
    {
    }
}
