//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;

namespace RTPuzzle
{
    public class AILogicColliderModule : RTPuzzle.InteractiveObjectModule, IAILogicColliderModuleDataRetriever
    {
        #region Internal Dependencies
        private AIObjectDataRetriever AIObjectDataRetirever;
        #endregion

        public IInteractiveObjectTypeDataRetrieval IInteractiveObjectTypeDataRetrieval { get; private set; }

        #region State
        private BoxCollider associatedCollider;
        #endregion

        #region Data Retrieval
        public BoxCollider GetCollider()
        {
            return this.associatedCollider;
        }
        #endregion

        public override void Init(InteractiveObjectInitializationObject interactiveObjectInitializationObject, IInteractiveObjectTypeDataRetrieval IInteractiveObjectTypeDataRetrieval,
            IInteractiveObjectTypeEvents IInteractiveObjectTypeEvents)
        {
            this.AIObjectDataRetirever = interactiveObjectInitializationObject.ParentAIObjectTypeReference;
            this.associatedCollider = GetComponent<BoxCollider>();
            this.IInteractiveObjectTypeDataRetrieval = IInteractiveObjectTypeDataRetrieval;
        }

        public void Tick(float d, float timeAttenuationFactor)
        {
        }

        #region Physics Events
        private void OnTriggerEnter(Collider other)
        {
            var collisionType = other.GetComponent<CollisionType>();
            if (collisionType != null)
            {
                if (collisionType.IsTargetZone)
                {
                    TargetZoneModule.FromCollisionType(collisionType).GetITargetZoneModuleEvent()
                        .OnAITriggerEnter(this.AIObjectDataRetirever);
                }

            }
        }

        private void OnTriggerStay(Collider other)
        {
            var collisionType = other.GetComponent<CollisionType>();
            if (collisionType != null)
            {
                if (collisionType.IsTargetZone)
                {
                    TargetZoneModule.FromCollisionType(collisionType).GetITargetZoneModuleEvent()
                           .OnAITriggerStay(this.AIObjectDataRetirever);
                }
            }
        }

        private void OnTriggerExit(Collider other)
        {
        }
        #endregion


        public static AIObjectDataRetriever FromCollisionType(CollisionType collisionType)
        {
            if (collisionType == null) { return null; }
            var AILogicColliderModule = collisionType.GetComponent<AILogicColliderModule>();
            if (AILogicColliderModule != null) { return AILogicColliderModule.GetComponentInParent<AIObjectType>(); }
            return null;
        }

        public static IAILogicColliderModuleDataRetriever AILogicColliderModuleFromCollisionType(CollisionType collisionType)
        {
            if (collisionType == null) { return null; }
            return collisionType.GetComponent<AILogicColliderModule>();
        }
    }

    public interface IAILogicColliderModuleListener
    {
        void OnAILogicColliderTriggerEnter(Collider other);

        void OnAILogicColliderTriggerStay(Collider other);

        void OnAILogicColliderTriggerExit(Collider other);
    }
}
