//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using UnityEngine;

namespace Editor_PuzzleCutsceneCreationWizard
{
    [System.Serializable]
    [CreateAssetMenu(fileName = "PuzzleCutsceneCreationWizardProfile", menuName = "CreationWizard/GameCreationWizardEditorProfile/PuzzleCutscene/PuzzleCutsceneCreationWizardProfile", order = 1)]
    public class PuzzleCutsceneCreationWizardProfile : AbstractCreationWizardEditorProfile
    {
        private List<CreationWizardOrderConfiguration> ModuleTypes_IMPL = new List<CreationWizardOrderConfiguration>() {
            new CreationWizardOrderConfiguration(typeof(EditorInformations), -1),
            new CreationWizardOrderConfiguration(typeof(PuzzleCutsceneConfigurationCreation), 0),
            new CreationWizardOrderConfiguration(typeof(PuzzleCutsceneGraphCreation), 1)
        };

        public override List<CreationWizardOrderConfiguration> ModulesConfiguration => this.ModuleTypes_IMPL;
    }
}