//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GameConfigurationID;
using UnityEngine;

namespace RTPuzzle
{
    [ModuleMetadata("Interactive", "Object that trigger event on collision.")]
    public class LaunchProjectileModuleDefinition : AbstractInteractiveObjectDefinition
    {
        [DrawConfiguration(ConfigurationType = typeof(LaunchProjectileConfiguration))]
        [CustomEnum(ConfigurationType = typeof(LaunchProjectileConfiguration))]
        public LaunchProjectileID LaunchProjectileID;

        public override void CreateObject(Transform parent)
        {
            var launchProjectileModule = MonoBehaviour.Instantiate(PuzzleGameSingletonInstances.PuzzleStaticConfigurationContainer.GetPuzzlePrefabConfiguration().BaseLaunchProjectileModule, parent);
            launchProjectileModule.LaunchProjectileID = this.LaunchProjectileID;
        }
    }
}
