//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;

namespace RTPuzzle
{
    [ModuleMetadata(header: "AI", shortDescription: "Collider used for triggering AI Events.")]
    public class AILogicColliderModuleDefinition : AbstractInteractiveObjectDefinition
    {
        public Vector3 Center;
        public Vector3 Size;

        public override void CreateObject(Transform parent)
        {
            var AILogicColliderModule = MonoBehaviour.Instantiate(PuzzleGameSingletonInstances.PuzzleStaticConfigurationContainer.GetPuzzlePrefabConfiguration().BaseAILogicColliderModule, parent);
            var boxCollider = AILogicColliderModule.GetComponent<BoxCollider>();
            boxCollider.center = this.Center;
            boxCollider.size = this.Size;
        }
    }
}
