//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;

namespace RTPuzzle
{
    [ModuleMetadata("General")]
    public class ModelObjectModuleDefinition : AbstractInteractiveObjectDefinition
    {
        public GameObject ModelPrefab;

        public override void CreateObject(Transform parent)
        {
            MonoBehaviour.Instantiate(PuzzleGameSingletonInstances.PuzzleStaticConfigurationContainer.GetPuzzlePrefabConfiguration().BaseModelObjectModule, parent);
        }
    }
}
