//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using AdventureGame;
using Editor_MainGameCreationWizard;
using GameConfigurationID;
using RTPuzzle;
using UnityEditor;

namespace Editor_RangeTypeObjectDefinitionCreationWizard
{
    [System.Serializable]
    public class RangeTypeObjectDefinitionConfigurationCreation : CreateableScriptableObjectComponent<RangeTypeObjectDefinitionInherentData>
    {
        public override void OnGenerationClicked(AbstractCreationWizardEditorProfile editorProfile)
        {
            var editorInfomrationsData = editorProfile.GetModule<EditorInformations>().EditorInformationsData;
            this.CreateAsset(InstancePath.RangeTypeObjectDefinitionInherentDataPath, editorInfomrationsData.RangeTypeObjectDefinitionID.ToString() + NameConstants.RangeTypeObjectDefinitionInherentData, editorProfile);
            this.AddToGameConfiguration(editorInfomrationsData.RangeTypeObjectDefinitionID, editorInfomrationsData.CommonGameConfigurations.PuzzleGameConfigurations.RangeTypeObjectDefinitionConfiguration, editorProfile);
        }
    }
}