//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;
using UnityEngine;

namespace Editor_PointOfInterestVisualMovementCreationWizard
{
    [System.Serializable]
    [CreateAssetMenu(fileName = "PointOfInterestVisualMovementCreationWizardProfile", menuName = "CreationWizard/GameCreationWizardEditorProfile/PointOfInterestVisualMovement/PointOfInterestVisualMovementCreationWizardProfile", order = 1)]
    public class PointOfInterestVisualMovementCreationWizardProfile : AbstractCreationWizardEditorProfile
    {
        private List<CreationWizardOrderConfiguration> ModuleTypes_IMPL = new List<CreationWizardOrderConfiguration>() {
            new CreationWizardOrderConfiguration(typeof(EditorInformations), -1),
            new CreationWizardOrderConfiguration(typeof(PointOfInterestVisualMovementConfigurationCreation), 0),
        };

        public override List<CreationWizardOrderConfiguration> ModulesConfiguration => this.ModuleTypes_IMPL;
    }
}