//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GameConfigurationID;
using UnityEngine;

namespace RTPuzzle
{
    [ModuleMetadata("Interactive", "Object can be repelled.")]
    public class ObjectRepelModuleDefinition : AbstractInteractiveObjectDefinition
    {
        [DrawConfiguration(ConfigurationType = typeof(ObjectRepelConfiguration))]
        [CustomEnum(ConfigurationType = typeof(ObjectRepelConfiguration))]
        public ObjectRepelID ObjectRepelID;

        [WireBox(R = 1, G = 0, B = 0, CenterFieldName = nameof(ObjectRepelModuleDefinition.Center), SizeFieldName = nameof(ObjectRepelModuleDefinition.Size))]
        public Vector3 Center;
        public Vector3 Size;

        public override void CreateObject(Transform parent)
        {
            var objectRepelModule = MonoBehaviour.Instantiate(PuzzleGameSingletonInstances.PuzzleStaticConfigurationContainer.GetPuzzlePrefabConfiguration().BaseObjectRepelModule, parent);

            var boxCollider = objectRepelModule.GetComponent<BoxCollider>();
            boxCollider.center = this.Center;
            boxCollider.size = this.Size;

            objectRepelModule.ObjectRepelID = this.ObjectRepelID;
        }
    }
}
