//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTPuzzle
{
    using UnityEngine;
    using ConfigurationEditor;
    using GameConfigurationID;
    using System.Collections.Generic;
    
    
    [System.Serializable()]
    [UnityEngine.CreateAssetMenu(fileName="AIPatrolGraphConfiguration", menuName="Configuration/PuzzleGame/AIPatrolGraphConfiguration/AIPatrolGraphConfiguration", order=1)]
    public class AIPatrolGraphConfiguration : ConfigurationEditor.ConfigurationSerialization<AIPatrolGraphID, AIPatrolGraphInherentData>
    {
    }
}
