//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTPuzzle
{
    
    
    public class InteractiveObjectTypeConfiguration
    {
        
        public static System.Collections.Generic.Dictionary<System.Type, System.Action<RTPuzzle.InteractiveObjectInitializationObject, RTPuzzle.InteractiveObjectType>> InitializationConfiguration = new System.Collections.Generic.Dictionary<System.Type, System.Action<InteractiveObjectInitializationObject, InteractiveObjectType>>(){
{typeof(RTPuzzle.ModelObjectModule),InteractiveObjectModulesInitializationOperations.InitializeModelObjectModule},
{typeof(RTPuzzle.AttractiveObjectModule),InteractiveObjectModulesInitializationOperations.InitializeAttractiveObjectModule},
{typeof(RTPuzzle.ObjectRepelModule),InteractiveObjectModulesInitializationOperations.InitializeObjectRepelModule},
{typeof(RTPuzzle.LevelCompletionTriggerModule),InteractiveObjectModulesInitializationOperations.InitializeLevelCompletionTriggerModule},
{typeof(RTPuzzle.TargetZoneModule),InteractiveObjectModulesInitializationOperations.InitializeTargetZoneModule},
{typeof(RTPuzzle.LaunchProjectileModule),InteractiveObjectModulesInitializationOperations.InitializeLaunchProjectileModule},
{typeof(RTPuzzle.DisarmObjectModule),InteractiveObjectModulesInitializationOperations.InitializeDisarmObjectModule},
{typeof(RTPuzzle.ActionInteractableObjectModule),InteractiveObjectModulesInitializationOperations.InitializeActionInteractableObjectModule},
{typeof(RTPuzzle.GrabObjectModule),InteractiveObjectModulesInitializationOperations.InitializeGrabObjectModule},
{typeof(RTPuzzle.InteractiveObjectCutsceneControllerModule),InteractiveObjectModulesInitializationOperations.InitializeInteractiveObjectCutsceneControllerModule},
{typeof(RTPuzzle.NearPlayerGameOverTriggerModule),InteractiveObjectModulesInitializationOperations.InitializeNearPlayerGameOverTriggerModule},
{typeof(RTPuzzle.ObjectSightModule),InteractiveObjectModulesInitializationOperations.InitializeObjectSightModule},
{typeof(RTPuzzle.AILogicColliderModule),InteractiveObjectModulesInitializationOperations.InitializeAILogicColliderModule},
{typeof(RTPuzzle.InRangeColliderTrackerModule),InteractiveObjectModulesInitializationOperations.InitializeInRangeColliderTrackerModule},
};
    }
}
