//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTPuzzle
{
    using GameConfigurationID;
    using System.Collections.Generic;
    using UnityEngine;
    using UnityEngine.AI;

    [System.Serializable()]
    [UnityEngine.CreateAssetMenu(fileName = "AIObjectTypeDefinitionInherentData", menuName = "Configuration/PuzzleGame/AIObjectTypeDefinitionConfiguration/AIObjectTypeDefiniti" +
        "onInherentData", order = 1)]
    public class AIObjectTypeDefinitionInherentData : ScriptableObject
    {
        [DrawDefinition(ConfigurationType = typeof(InteractiveObjectTypeDefinitionConfiguration))]
        [CustomEnum(ConfigurationType = typeof(InteractiveObjectTypeDefinitionConfiguration))]
        public InteractiveObjectTypeDefinitionID InteractiveObjectTypeDefinitionID;
        
        [CustomEnum()]
        public AIObjectID AIObjectID;
        
        [Inline(CreateAtSameLevelIfAbsent = true)]
        public GenericPuzzleAIComponentsV2 GenericPuzzleAIComponents;

        public void DefineAIObject(AIObjectType aIObjectType, PuzzlePrefabConfiguration puzzlePrefabConfiguration, PuzzleGameConfiguration puzzleGameConfiguration)
        {
            DefineAI(aIObjectType);
            DefineInteractiveObject(aIObjectType, puzzlePrefabConfiguration, puzzleGameConfiguration);
        }

        private void DefineInteractiveObject(AIObjectType aIObjectType, PuzzlePrefabConfiguration puzzlePrefabConfiguration, PuzzleGameConfiguration puzzleGameConfiguration)
        {
            if (this.InteractiveObjectTypeDefinitionID != InteractiveObjectTypeDefinitionID.NONE)
            {
                puzzleGameConfiguration.InteractiveObjectTypeDefinitionConfiguration.ConfigurationInherentData.TryGetValue(this.InteractiveObjectTypeDefinitionID, out InteractiveObjectTypeDefinitionInherentData InteractiveObjectTypeDefinitionInherentData);
                if (InteractiveObjectTypeDefinitionInherentData != null)
                {
                    var InteractiveObjectType = aIObjectType.gameObject.AddComponent<InteractiveObjectType>();
                    InteractiveObjectTypeDefinitionInherentData.DefineInteractiveObject(InteractiveObjectType, puzzlePrefabConfiguration, puzzleGameConfiguration);
                }
            }
        }

        private void DefineAI(AIObjectType aIObjectType)
        {
            aIObjectType.AiID = this.AIObjectID;

            var aiManagers = new List<InterfaceAIManager>();
            foreach (var definitionModuleAction in this.GenericPuzzleAIComponents.RangeDefinitionModulesActivation)
            {
                if (definitionModuleAction.Value)
                {
                    var moduleConfiguration = this.GenericPuzzleAIComponents.RangeDefinitionModules[definitionModuleAction.Key];

                    if (moduleConfiguration.GetType().IsSubclassOf(typeof(AbstractAIComponent)))
                    {
                        aiManagers.Add(((AbstractAIComponent)moduleConfiguration).BuildManager());
                    }
                }
            }
            aIObjectType.AiManagers = aiManagers;

            this.CreateNavMeshAgentIfNecessary(aIObjectType);
        }

        private void CreateNavMeshAgentIfNecessary(AIObjectType aIObjectType)
        {
            if (aIObjectType.GetComponent<NavMeshAgent>() == null)
            {
                var aiAgent = aIObjectType.gameObject.AddComponent<NavMeshAgent>();
                aiAgent.baseOffset = 0f;
                aiAgent.speed = 0f;
                aiAgent.angularSpeed = 120f;
                aiAgent.acceleration = 999999f;
                aiAgent.stoppingDistance = 0f;
                aiAgent.autoBraking = true;
                aiAgent.radius = 0.5f;
                aiAgent.height = 2f;
                aiAgent.avoidancePriority = 50;
                aiAgent.autoTraverseOffMeshLink = true;
                aiAgent.autoRepath = true;
            }
        }
    }
}
