//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Editor_MainGameCreationWizard;
using GameConfigurationID;
using RTPuzzle;
using UnityEditor;

namespace Editor_PuzzleCutsceneCreationWizard
{
    [System.Serializable]
    public class PuzzleCutsceneConfigurationCreation : CreateableScriptableObjectComponent<PuzzleCutsceneInherentData>
    {
        public override void OnGenerationClicked(AbstractCreationWizardEditorProfile editorProfile)
        {
            var editorInfomrationsData = editorProfile.GetModule<EditorInformations>().EditorInformationsData;
            var PuzzleCutsceneConfiguration = editorInfomrationsData.CommonGameConfigurations.PuzzleGameConfigurations.PuzzleCutsceneConfiguration;
            this.CreateAsset(InstancePath.GetConfigurationDataPath(PuzzleCutsceneConfiguration), editorInfomrationsData.PuzzleCutsceneID.ToString() + "_" + 
                this.GetType().BaseType.GetGenericArguments()[0].Name, editorProfile);
            this.AddToGameConfiguration(editorInfomrationsData.PuzzleCutsceneID, PuzzleCutsceneConfiguration, editorProfile);
        }
    }
}