//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Editor_GameDesigner;
using RTPuzzle;
using UnityEditor;
using UnityEngine;

namespace Editor_GameCustomEditors
{
    [ExecuteInEditMode]
    [CustomEditor(typeof(NearPlayerGameOverTriggerModule))]
    public class NearPlayerGameOverTriggerCustomEditor : AbstractGameCustomEditorWithLiveSelection<NearPlayerGameOverTriggerModule, NearPlayerGameOverTriggerCustomEditorContext, NearPlayerGameOverTriggerConfigurationModule, EditNearPlayerGameOverTrigger>
    {
        private void OnEnable()
        {
            if (this.target != null)
            {
                this.context = new NearPlayerGameOverTriggerCustomEditorContext();
                this.context.NearPlayerGameOverTriggerModule = (NearPlayerGameOverTriggerModule)target;
                var NearPlayerGameOverTriggerConfiguration = AssetFinder.SafeSingleAssetFind<NearPlayerGameOverTriggerConfiguration>("t:" + typeof(NearPlayerGameOverTriggerConfiguration));
                if (NearPlayerGameOverTriggerConfiguration.ConfigurationInherentData.ContainsKey(this.context.NearPlayerGameOverTriggerModule.NearPlayerGameOverTriggerID))
                {
                    this.context.NearPlayerGameOverTriggerInherentData = NearPlayerGameOverTriggerConfiguration.ConfigurationInherentData[this.context.NearPlayerGameOverTriggerModule.NearPlayerGameOverTriggerID];
                    this.drawModules = new System.Collections.Generic.List<GUIDrawModule<NearPlayerGameOverTriggerModule, NearPlayerGameOverTriggerCustomEditorContext>>() {
                        new NearPlayerRangeComponent()
                    };
                }
            }
        }
    }

    public class NearPlayerGameOverTriggerCustomEditorContext
    {
        public NearPlayerGameOverTriggerModule NearPlayerGameOverTriggerModule;
        public NearPlayerGameOverTriggerInherentData NearPlayerGameOverTriggerInherentData;
    }


    public class NearPlayerRangeComponent : GUIDrawModule<NearPlayerGameOverTriggerModule, NearPlayerGameOverTriggerCustomEditorContext>
    {
        public override void SceneGUI(NearPlayerGameOverTriggerCustomEditorContext context, NearPlayerGameOverTriggerModule target)
        {
            if (context.NearPlayerGameOverTriggerInherentData != null)
            {
                Handles.color = Color.magenta;
                var labelStyle = new GUIStyle(EditorStyles.label);
                labelStyle.normal.textColor = Color.magenta;
                Handles.Label(target.transform.position + (Vector3.up * context.NearPlayerGameOverTriggerInherentData.NearPlayerDetectionRadius), "Near player game over radius.", labelStyle);
                Handles.DrawWireDisc(target.transform.position, Vector3.up, context.NearPlayerGameOverTriggerInherentData.NearPlayerDetectionRadius);
            }
        }
    }

}