//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GameConfigurationID;
using UnityEngine;

namespace RTPuzzle
{


    public class GrabObjectModule : RTPuzzle.InteractiveObjectModule
    {

        #region External Dependencies
        private PlayerActionPuzzleEventsManager PlayerActionPuzzleEventsManager;
        #endregion


        [CustomEnum()]
        public GameConfigurationID.GrabObjectID GrabObjectID;

        private InteractiveObjectType parentInteractiveObject;
        private GrabObjectInherentData GrabObjectInherentData;
        private GrabObjectAction grabObjectAction;

        #region Data Retrieval
        public GrabObjectAction GrabObjectAction { get => grabObjectAction; }
        public InteractiveObjectType ParentInteractiveObject { get => parentInteractiveObject; }
        #endregion

        public void Init(GrabObjectInherentData GrabObjectInherentData)
        {
            #region External Dependencies
            this.PlayerActionPuzzleEventsManager = GameObject.FindObjectOfType<PlayerActionPuzzleEventsManager>();
            #endregion
            this.parentInteractiveObject = GetComponentInParent<InteractiveObjectType>();
            this.GrabObjectInherentData = GrabObjectInherentData;

            var sphereCollider = this.GetComponent<SphereCollider>();
            sphereCollider.radius = this.GrabObjectInherentData.EffectRadius;

            this.grabObjectAction = new GrabObjectAction(new GrabActionInherentData(this.GrabObjectID, PlayerActionId._1_Town_StartTurorial_SpeakerProjectile, SelectionWheelNodeConfigurationId.GRAB_CONTEXT_ACTION_WHEEL_CONFIG, 0f));
        }

        public virtual void Tick(float d, float timeAttenuationFactor)
        {
        }

        private void OnTriggerEnter(Collider other)
        {
            var collisionType = other.GetComponent<CollisionType>();
            if (collisionType != null && collisionType.IsPlayer)
            {
                this.PlayerActionPuzzleEventsManager.OnGrabObjectEnter(this);
            }
        }

        public void OnInteractiveObjectDestroyed()
        {
            this.PlayerActionPuzzleEventsManager.OnGrabObjectExit(this);
        }

        private void OnTriggerExit(Collider other)
        {
            var collisionType = other.GetComponent<CollisionType>();
            if (collisionType != null && collisionType.IsPlayer)
            {
                this.PlayerActionPuzzleEventsManager.OnGrabObjectExit(this);
            }
        }

    }
}
