//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTPuzzle
{
    using GameConfigurationID;
    using UnityEngine;
    using UnityEngine.Serialization;

    [System.Serializable()]
    [UnityEngine.CreateAssetMenu(fileName="GrabObjectInherentData", menuName="Configuration/PuzzleGame/GrabObjectConfiguration/GrabObjectInherentData", order=1)]
    public class GrabObjectInherentData : ScriptableObject
    {
        [WireCircle(R = 1, G = 0, B = 1)]
        public float EffectRadius;

        [FormerlySerializedAs("PlayerActionToIncrement")]
        [CustomEnum()]
        public PlayerActionId PlayerActionToIncrementOrAdd;
    }
}
