//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID {
  
  
  [System.Serializable()]
  public enum ActionInteractableObjectID {
    
    TEST = 0,
    
    _1_Town_GardenDoor = 1,

        TEST_1 = 2,
        TEST_2 = 3
    }
}
