//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID
{
    [System.Serializable()]
    public enum AIObjectID
    {
        _Sewers_1_Mouse = 0,

        RTP_PUZZLE_CREATION = 6,

        _Sewers_2_Mouse = 7,

        _1_Town_GardenWatchman = 9,

        _1_Town_StartTutorial_AITest = 11,

        TEST_1 = 12
    }
}
