//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID
{


    [System.Serializable()]
    public enum AIPatrolGraphID
    {

        NONE = 0,

        _1_Town_StartTutorial_Speaker = 1,

        _Town1_Park_ToSewerPuzzle_FrontGuard_1 = 2,

        _Town1_Park_ToSewerPuzzle_FrontGuard_2 = 3,

        _Town1_Park_ToSewerPuzzle_FrontGuard_3 = 4
    }
}
