//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID
{


    [System.Serializable()]
    public enum AIPositionMarkerID
    {

        _1_Town_GardenWatchman_1 = 0,

        _1_Town_GardenWatchman_2 = 1,

        _Town1_Park_ToSewerPuzzle_FrontGuard_1_1 = 2,
        _Town1_Park_ToSewerPuzzle_FrontGuard_1_2 = 3,
        _Town1_Park_ToSewerPuzzle_FrontGuard_1_3 = 4,
        _Town1_Park_ToSewerPuzzle_FrontGuard_1_4 = 5,
        _Town1_Park_ToSewerPuzzle_FrontGuard_1_5 = 6,
        _Town1_Park_ToSewerPuzzle_FrontGuard_1_6 = 7,
        _Town1_Park_ToSewerPuzzle_FrontGuard_1_7 = 8,


        _Town1_Park_ToSewerPuzzle_FrontGuard_2_1 = 9,
        _Town1_Park_ToSewerPuzzle_FrontGuard_2_2 = 10,
        _Town1_Park_ToSewerPuzzle_FrontGuard_2_3 = 11,
        _Town1_Park_ToSewerPuzzle_FrontGuard_2_4 = 12,
        _Town1_Park_ToSewerPuzzle_FrontGuard_2_5 = 13,
        _Town1_Park_ToSewerPuzzle_FrontGuard_2_6 = 14,
        _Town1_Park_ToSewerPuzzle_FrontGuard_2_7 = 15,
        _Town1_Park_ToSewerPuzzle_FrontGuard_2_8 = 16,

        _Town1_Park_ToSewerPuzzle_FrontGuard_3_1 = 17,

        TEST_1 = 18,
        TEST_2 = 19
    }
}
