//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID {
  
  
  [System.Serializable()]
  public enum AnimationID {
    
    NONE = 0,
    
    ACTION_FORBIDDEN = 1,
    
    ACTION_GIVE_OBJECT_0 = 2,
    
    ACTION_GIVE_OBJECT_1 = 3,
    
    ACTION_CA_POCKET_ITEM = 4,
    
    ACTION_CA_POCKET_ITEM_LAY = 5,
    
    ACTION_CA_PROJECTILE = 6,
    
    ACTION_CA_PROJECTILE_THROW = 7,
    
    ACTION_LISTENING = 8,
    
    IDLE_SMOKE_0 = 10,
    
    IDLE_SMOKE_1 = 11,
    
    ADDITIONAL_CONTEXT_ACTION_LISTENING = 12,
    
    PLAYER_JACKET_CORD_JITTER_TREE = 13,
    
    SEWER_DOOR_OPEN = 14,
    
    BACK_TO_WALL_POSE = 15,
    
    ADVENTURE_MOVEMENT = 16,
    
    PUZZLE_MOVEMENT = 17,
    
    FEAR = 18,
    
    HITTED_BY_PROJECTILE_1ST = 19,
    
    HITTED_BY_PROJECTILE_2ND = 20,
    
    POSE_OVERRIVE_LISTENING = 21,
    
    _1_Town_Bouncer_PlayerExamination = 22,
    
    EDITOR_TEST = 23,
    
    _1_Town_Thief_StealIDCard = 24,
    
    _1_Town_Thief_ArriveFromAbove = 25,
    
    _1_Town_Thief_EscapeTroughGardenFence = 26,
    
    _1_Town_Thief_EscapeHandWave = 27,
    
    POSE_ArmsGrabVerticalBars = 28,
    
    ACTION_GRAB_DOWN = 29,
    
    GENERIC_SquatDown_Idle = 30,
    
    GENERIC_SquatDown = 31,
    
    CA_CrushDownItem = 32,
    
    _1_Town_GardenDoor_Open = 33,
    
    CA_PushWithViolence_0 = 34,
    
    POSE_DrawGun = 35,
    
    CA_PushWithViolence_1 = 36,
    
    POSE_FallDown = 37,
    
    _1_Town_Park_BatFly = 38,
  }
}
