//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID {
  
  
  [System.Serializable()]
  public enum AnimationLayerID {
    
    Base_Layer = 0,
    
    Empty_Layer = 1,
    
    Context_Action_Override = 2,
    
    Additional_Action_Override = 3,
    
    POICutscene = 5,
    
    Pose_Override = 6,
    
    Movement = 7,
  }
}
