//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID
{


    [System.Serializable()]
    public enum AttractiveObjectId
    {

        CHEESE = 0,

        EDITOR_TEST = 1,

        CHEESE_SEWER_RTP_2 = 2,

        RTP_TEST_RangeEffectManager = 3,

        _1_Town_StartTutorial_Speaker = 4,

        TEST_PROJECTILE_TOATTRACTIVE = 5,

        _1_Town_StartTutorial_Test = 6,
    }
}
