//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID
{


    [System.Serializable()]
    public enum AttractiveObjectId
    {

        _Sewers_1_CheeseAttractive = 0,
        
        _Sewers_2_CheeseAttractive = 2,

        RTP_TEST_RangeEffectManager = 3,

        _1_Town_StartTutorial_Speaker = 4,

        _1_Town_StartTutorial_Test = 6,

        TEST_1 = 7,

        TEST_2 = 8
    }
}
