//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID
{


    [System.Serializable()]
    public enum CutscenePositionMarkerID
    {

        PLAYER_POSITION_1 = 0,

        PLAYER_POSITION_2 = 1,

        PLAYER_POSITION_3 = 2,

        PLAYER_POSITION_4 = 3,

        PLAYER_POSITION_5 = 10,

        _1_Town_Thief_Spawn = 4,

        _1_Town_Thief_Position_1 = 5,

        _1_Town_Thief_Position_2 = 6,

        _1_Town_Thief_Position_3 = 7,
        _1_Town_Thief_Position_4 = 8,
        _1_Town_Thief_Position_5 = 9,
    }
}
