//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID {
  
  
  [System.Serializable()]
  public enum CutsceneId {
    
    PLAYER_DUMPSTER_GRAB = 0,
    
    PLAYER_OPEN_SEWER = 1,
    
    AI_TEST = 2,
  }
}
