//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID
{


    [System.Serializable()]
    public enum DisarmObjectID
    {

        RTP_CREATION_TEST = 0,

        _1_Town_Start_Tutorial_Speaker = 1,

        TEST_1 = 4,
        TEST_2 = 5
    }
}
