//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID {
  
  
  [System.Serializable()]
  public enum DiscussionTreeId {
    
    SEWER_RTP_1_DOOR = 2,
    
    _1_Town_Bouncer_AskID = 3,
    
    _1_Town_GardenWatchman_Forbidden = 4,
    
    _1_Town_Girl_ToParkInfiltration = 5,
  }
}
