//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID {
  
  
  [System.Serializable()]
  public enum DiscussionTreeId {
    
    BOUNCER_DISCUSSION_TREE = 0,
    
    BOUNCER_OK_DISCUSSION = 1,
    
    SEWER_RTP_1_DOOR = 2,
  }
}
