//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID {
  
  
  [System.Serializable()]
  public enum DiscussionNodeId {
    
    NONE = 0,
    
    A = 1,
    
    B = 2,
    
    C = 3,
    
    D = 4,
    
    E = 5,
    
    F = 6,
    
    G = 7,
    
    H = 8,
    
    I = 9,
    
    J = 10,
    
    K = 11,
    
    L = 12,
    
    M = 13,
    
    N = 14,
    
    O = 15,
    
    P = 16,
    
    Q = 17,
    
    _1_Town_EnterPuzzle = 18,
  }
}
