//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID {
  
  
  [System.Serializable()]
  public enum DisucssionSentenceTextId {
    
    SWER_RTP_1_DOOR = 0,
    
    _1_Town_Bouncer_AskID = 1,
    
    _1_Town_GardenWatchman_Forbidden_NodeEditor_1 = 2,
    
    _1_Town_GardenWatchman_Forbidden_NodeEditor_2 = 3,
    
    _1_Town_GardenWatchman_Forbidden_NodeEditor_3 = 4,
    
    _1_Town_GardenWatchman_Forbidden_NodeEditor_4 = 5,
    
    _1_Town_GardenWatchman_Forbidden_NodeEditor_5 = 6,
    
    _1_Town_GardenWatchman_Forbidden_NodeEditor_6 = 7,
    
    _1_Town_GardenWatchman_Forbidden_NodeEditor_7 = 8,
  }
}
