//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID
{


    [System.Serializable()]
    public enum GrabObjectID
    {

        NONE = 0,

        _1_Town_StartTutorial_Speaker = 1,
        _1_Town_StartTutorial_Test = 2,
        TEST_1 = 3,
        TEST_2 = 4
    }
}
