//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID
{
    [System.Serializable()]
    public enum InteractiveObjectID
    {
        NONE = 0,
        Player = 1,
        _1_Town_GardenDoor = 2,
        _1_Town_StartTutorial_Test_Speaker = 3,
        _1_Town_GardenWatchman = 4
    }
}
