//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID {
  
  
  [System.Serializable()]
  public enum InteractiveObjectTypeDefinitionID {
    
    NONE = 0,
    
    _1_Town_StartTutorial_TargetZone = 1,
    
    _Sewers_1_TargetZone = 2,
    
    _Sewers_2_TargetZone = 3,
    
    OneAIForcedTargetZone_Test = 4,
    
    OneAIForcedHighDistanceTargetZone_Test = 5,
    
    _1_Town_GardenWatchman = 7,
    
    _1_Town_GardenDoor = 8,
    
    Player = 9,
    
    _1_Town_StartTutorial_Speaker = 10,

    TEST_1 = 11
  }
}
