//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID {
  
  
  [System.Serializable()]
  public enum LaunchProjectileId {
    
    STONE = 0,
    
    STONE_1 = 1,
    
    RTP_PUZZLE_CREATION_TEST = 2,
    
    SEWER_RTP_2_STONE = 3,

    _1_Town_StartTutorial_Speaker = 5,
    
    TEST_PROJECTILE_EXPLODE = 6,
  }
}
