//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID
{


    [System.Serializable()]
    public enum LaunchProjectileID
    {

        _Sewers_1_Projectile = 0,

        STONE_1 = 1,

        RTP_PUZZLE_CREATION_TEST = 2,

        _Sewers_2_Projectile = 3,

        _1_Town_StartTutorial_Speaker = 5,

        _1_Town_StartTutorial_Test = 8,

        TEST_1 = 9,
        TEST_2 = 10,
        TEST_3 = 11
    }
}
