//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID
{


    [System.Serializable()]
    public enum LevelZoneChunkID
    {

        SEWER_RTP_1 = 0,

        SEWER_RTP_2 = 1,

        RTP_PUZZLE_CREATION_TEST_CHUNK = 2,

        _1_Town_MainRoad = 3,

        RTP_PUZZLE_CREATION_TEST = 4,

        RTP_TEST_OBSTACLES = 5,

        RTP_TEST_RangeEffectManager = 6,

        ADVENTURE_AnimationCutsceneTimelineTest = 7,

        NONE = 8,

        _Town1_Park = 9,

        _Town1_Park_ToSewerPuzzle = 10,

        ADVENTURE_PlayerSelectionTest = 11
    }
}
