//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID {
  
  
  public enum LevelZonesID {
    
    LEVEL1 = 0,
    
    SEWER = 1,
    
    SEWER_RTP = 2,
    
    RTP_TEST = 3,
    
    RTP_EDITOR_TEST = 4,
    
    SEWER_ADVENTURE = 5,
    
    RTP_PUZZLE_CREATION_TEST = 6,
    
    SEWER_RTP_2 = 7,
    
    ADVENTURE_EDITOR_TEST = 8,
  }
}
