//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID
{


    [System.Serializable()]
    public enum PlayerActionId
    {

        NONE = 0,

        STONE_PROJECTILE_ACTION_1 = 1,

        CHEESE_ATTRACTIVE_ACTION_1 = 2,

        ATTRACTIVE_ACTION_EDITOR_TEST = 3,

        RTP_PUZZLE_CREATION_TEST = 4,

        SEWER_RTP_2_STONE_PROJECTILE = 5,

        _1_Town_StartTurorial_SpeakerProjectile = 6,

        _1_Town_StartTutorial_GardenDoorIntreaction = 7,

        TEST_1 = 8,
        TEST_2 = 9,
        TEST_3 = 10,
    }
}
