//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID {
  
  
  [System.Serializable()]
  public enum PlayerActionId {
    
    STONE_PROJECTILE_ACTION_1 = 0,
    
    CHEESE_ATTRACTIVE_ACTION_1 = 1,
    
    ATTRACTIVE_ACTION_EDITOR_TEST = 2,
    
    RTP_PUZZLE_CREATION_TEST = 3,
    
    SEWER_RTP_2_STONE_PROJECTILE = 4,
  }
}
