//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID {
  
  
  [System.Serializable()]
  public enum PointOfInterestId {
    
    NONE = 0,
    
    PLAYER = 4,
    
    SEWER_ENTRANCE = 7,
    
    SEWER_EXIT = 8,
    
    SEWER_TO_PUZZLE = 9,
    
    SEWER_TO_PUZZLE_2 = 12,
    
    SEWER_RTP_1_DOOR = 13,
    
    _1_Town_Girl = 14,
    
    RTP_PUZZLE_CREATION_TEST = 9999,
    
    _1_Town_Bouncer = 10000,
    
    _1_Town_Thief = 10001,
  }
}
