//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID
{


    [System.Serializable()]
    public enum PointOfInterestVisualMovementID
    {

        NONE = 0,

        PLAYER = 4,

        SEWER_ENTRANCE = 7,

        SEWER_EXIT = 8,

        SEWER_TO_PUZZLE = 9,

        SEWER_TO_PUZZLE_2 = 12,

        SEWER_RTP_1_DOOR = 13,

        _1_Town_Girl = 14,

        _1_Town_Bouncer = 16,

        _1_Town_Thief = 17,

        _1_Town_GardenDoor = 18,

        _1_Town_GardenWatchman = 19,

        _Town1_PuzzleIntroductionCutscene = 20,

        TEST_1 = 21,

        TEST_2 = 22
    }
}
