//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID {
  
  
  [System.Serializable()]
  public enum PointOfInterestId {
    
    NONE = 0,
    
    BOUNCER = 1,
    
    ID_CARD = 2,
    
    ID_CARD_V2 = 3,
    
    PLAYER = 4,
    
    DUMBSTER = 5,
    
    CROWBAR = 6,
    
    SEWER_ENTRANCE = 7,
    
    SEWER_EXIT = 8,
    
    SEWER_TO_PUZZLE = 9,
    
    CROWBAR_INVENTORY = 10,
    
    ID_CARD_INVENTORY = 11,
    
    SEWER_TO_PUZZLE_2 = 12,
    
    SEWER_RTP_1_DOOR = 13,
    
    RTP_PUZZLE_CREATION_TEST = 9999,
  }
}
