//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID {
  
  
  [System.Serializable()]
  public enum PuzzleCutsceneID {
    
    NONE = 0,
    
    _1_Town_GardenDoor_InteractiveAction = 1,
    
    _GENERIC_NearPlayerGameOver = 2,
    
    TEST_0 = 3,
    
    TEST_1 = 4,
    
    TEST_2 = 5,
    
    _GENERIC_AnimationWithFollowObject = 6,
  }
}
