//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID
{


    [System.Serializable()]
    public enum RangeTypeObjectDefinitionID
    {
        NONE = 0,

        _1_Town_StartTutorial_TargetZone = 1,

        _1_Town_GardenWatchman = 2,

        INPUT_SphereRange_WithObstacleListener = 3,

        _Sewers_1_TargetZone = 4,

        _Sewers_2_TargetZone = 5,
    }
}
