//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID {
  
  
  [System.Serializable()]
  public enum RepelableObjectID {
    
    CHEESE_SEWER_RTP_2 = 0,
    
    RTP_PUZZLE_CREATION_TEST = 1,
    
    CHEESE_SEWER_RTP_2_1 = 2,
    
    INTERACTION_TEST = 3,
  }
}
