//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID {
  
  
  [System.Serializable()]
  public enum ScenarioTimelineNodeID {
    
    Sewer_To_SewerRTP_1 = 9,
    
    Sewer_To_SewerRTP_2_Disabling = 10,
    
    SewerRTP2_Success = 11,
    
    SewerRTP1_DoorPOI = 12,
    
    SewerRTP1_DoorPOI_Open = 13,
    
    SewerRTP1_DoorPOI_Opening = 14,
    
    _1_Town_AfterStartCutscene = 15,
    
    _1_Town_BeforeStartCutscene = 16,
    
    GrabTest = 17,
    
    _1_Town_PuzzleTransition = 18,
    
    _1_Town_GardenWatchMan_Initialization = 19,
  }
}
