//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID {
  
  
  [System.Serializable()]
  public enum ScenarioTimelineNodeID {
    
    Crowbar_POI = 0,
    
    Crowbar_Inventory = 1,
    
    SewerEntrance_POI = 2,
    
    TransitionToSewer = 3,
    
    IDCard_Inventory = 4,
    
    Dumpster_POI = 5,
    
    Bouncer_POI = 6,
    
    IDCard_Grabbed = 7,
    
    IDCard_Grabbed_END = 8,
    
    Sewer_To_SewerRTP_1 = 9,
    
    Sewer_To_SewerRTP_2_Disabling = 10,
    
    SewerRTP2_Success = 11,
  }
}
