//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameConfigurationID {
  
  
  [System.Serializable()]
  public enum TargetZoneID {
    
    LEVEL1_TARGET_ZONE = 0,
    
    TEST_TARGET_ZONE = 1,
    
    RTP_PUZZLE_CREATION_TEST = 2,
    
    SEWER_RTP_2_TARGET_ZONE = 3,
    
    INTERACTION_TEST = 4,
    
    _1_Town_StartTutorial = 5,

        TEST_1 = 6,
        TEST_2 = 7
    }
}
