//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTPuzzle
{
    using UnityEngine;
    
    
    [System.Serializable()]
    [UnityEngine.CreateAssetMenu(fileName="AIPatrolGraphInherentData", menuName="Configuration/PuzzleGame/AIPatrolGraphConfiguration/AIPatrolGraphInherentData", order=1)]
    public class AIPatrolGraphInherentData : ScriptableObject
    {
        [Inline(createAtSameLevelIfAbsent: true)]
        public AIPatrolGraph AIPatrolGraph;
    }
}
