//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Editor_MainGameCreationWizard;
using GameConfigurationID;
using AdventureGame;
using UnityEditor;

namespace Editor_PointOfInterestVisualMovementCreationWizard
{
    [System.Serializable]
    public class PointOfInterestVisualMovementConfigurationCreation : CreateableScriptableObjectComponent<PointOfInterestVisualMovementInherentData>
    {
        public override void OnGenerationClicked(AbstractCreationWizardEditorProfile editorProfile)
        {
            var editorInfomrationsData = editorProfile.GetModule<EditorInformations>().EditorInformationsData;
            this.CreateAsset(InstancePath.PointOfInterestVisualMovementInherentDataPath, editorInfomrationsData.PointOfInterestVisualMovementID.ToString() + NameConstants.PointOfInterestVisualMovementInherentData, editorProfile);
            this.AddToGameConfiguration(editorInfomrationsData.PointOfInterestVisualMovementID, editorInfomrationsData.CommonGameConfigurations.GetConfiguration<PointOfInterestVisualMovementConfiguration>(), editorProfile);
        }
    }
}