//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GameConfigurationID;

namespace RTPuzzle
{
    
    
    public class DisarmObjectModuleDefinition : OdinSerializer.SerializedScriptableObject
    {
        [CustomEnum(ConfigurationType = typeof(DisarmObjectConfiguration))]
        public DisarmObjectID DisarmObjectID;

        public DisarmObjectInherentData DisarmObjectInherentData;
    }
}
