//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GameConfigurationID;
using UnityEngine;

namespace RTPuzzle
{
    
    
    public class DisarmObjectModuleDefinition : AbstractInteractiveObjectDefinition
    {
        [CustomEnum(ConfigurationType = typeof(DisarmObjectConfiguration))]
        public DisarmObjectID DisarmObjectID;

        public override void CreateObject(Transform parent)
        {
            var DisarmObjectModule = MonoBehaviour.Instantiate(PuzzleGameSingletonInstances.PuzzleStaticConfigurationContainer.PuzzleStaticConfiguration.PuzzlePrefabConfiguration.BaseDisarmObjectModule, parent);
            DisarmObjectModule.DisarmObjectID = this.DisarmObjectID;
        }
    }
}
