//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor_GameDesigner
{
    
    
    public class ChoiceTreeConstant
    {
        
        public static System.Collections.Generic.Dictionary<string, System.Type> Modules = new System.Collections.Generic.Dictionary<string, System.Type>(){
{"Level//.CreatePuzzleLevel",typeof(Editor_GameDesigner.CreatePuzzleLevel)},
{"Level//.CreateAdventureLevel",typeof(Editor_GameDesigner.CreateAdventureLevel)},
{"Level//.EditPuzzleLevel",typeof(Editor_GameDesigner.EditPuzzleLevel)},
{"Level//.CreateChunk",typeof(Editor_GameDesigner.CreateChunk)},
{"LevelChunk//Environmnent//.AddEnvironmentModel",typeof(Editor_GameDesigner.AddEnvironmentModel)},
{"LevelChunk//Environmnent//Obstacles//.AddNewObstacle",typeof(Editor_GameDesigner.AddNewObstacle)},
{"Puzzle//AI//.CreateAI",typeof(Editor_GameDesigner.CreateAI)},
{"Puzzle//AI//.AddAI",typeof(Editor_GameDesigner.AddAI)},
{"Puzzle//AI//.AIModel",typeof(Editor_GameDesigner.AIModel)},
{"Puzzle//AI//.ExploreAI",typeof(Editor_GameDesigner.ExploreAI)},
{"Puzzle//AI//.AIManagerModuleWizard",typeof(Editor_GameDesigner.AIManagerModuleWizard)},
{"Puzzle//AI//Behavior//.CreateBehavior",typeof(Editor_GameDesigner.CreateBehavior)},
{"Puzzle//AI//Behavior//.EditBehavior",typeof(Editor_GameDesigner.EditBehavior)},
{"Puzzle//Environment//.GroundEffectAdd",typeof(Editor_GameDesigner.GroundEffectAdd)},
{"Puzzle//TargetZone//.CreateTargetZone",typeof(Editor_GameDesigner.CreateTargetZone)},
{"Puzzle//TargetZone//.EditTargetZone",typeof(Editor_GameDesigner.EditTargetZone)},
{"Puzzle//TargetZone//.AddTargetZone",typeof(Editor_GameDesigner.AddTargetZone)},
{"Puzzle//TargetZone//.ExploreTargetZone",typeof(Editor_GameDesigner.ExploreTargetZone)},
{"Puzzle//Projectile//.CreateProjectile",typeof(Editor_GameDesigner.CreateProjectile)},
{"Puzzle//Projectile//.EditProjectile",typeof(Editor_GameDesigner.EditProjectile)},
{"Puzzle//Projectile//.ExploreProjectile",typeof(Editor_GameDesigner.ExploreProjectile)},
{"Puzzle//DisarmObject//.CreateDisarmObject",typeof(Editor_GameDesigner.CreateDisarmObject)},
{"Puzzle//DisarmObject//.EditDisarmObject",typeof(Editor_GameDesigner.EditDisarmObject)},
{"Puzzle//InteractiveObject//.CreateInteractiveObject",typeof(Editor_GameDesigner.CreateInteractiveObject)},
{"Puzzle//InteractiveObject//.InteractiveObjectExplorer",typeof(Editor_GameDesigner.InteractiveObjectExplorer)},
{"Puzzle//AttractiveObject//.CreateAttractiveObject",typeof(Editor_GameDesigner.CreateAttractiveObject)},
{"Puzzle//AttractiveObject//.EditAttractiveObject",typeof(Editor_GameDesigner.EditAttractiveObject)},
{"Puzzle//AttractiveObject//.ExploreAttractiveObject",typeof(Editor_GameDesigner.ExploreAttractiveObject)},
{"Puzzle//PlayerAction//.ExplorePlayerActions",typeof(Editor_GameDesigner.ExplorePlayerActions)},
{"Puzzle//PlayerAction//.CreatePlayerActions",typeof(Editor_GameDesigner.CreatePlayerActions)},
{"Puzzle//ContextMark//.ExploreContextMark",typeof(Editor_GameDesigner.ExploreContextMark)},
{"Puzzle//InteractiveObjects//.ExploreRepelableObject",typeof(Editor_GameDesigner.ExploreRepelableObject)},
{"Puzzle//InteractiveObjects//.CreateRepelableObject",typeof(Editor_GameDesigner.CreateRepelableObject)},
{"Puzzle//InteractiveObjects//.EditRepelableObject",typeof(Editor_GameDesigner.EditRepelableObject)},
{"Adventure//POI//.CreatePOI",typeof(Editor_GameDesigner.CreatePOI)},
{"Adventure//POI//.EditPOI",typeof(Editor_GameDesigner.EditPOI)},
{"Adventure//POI//.POIModel",typeof(Editor_GameDesigner.POIModel)},
{"Adventure//POI//.ExplorePOI",typeof(Editor_GameDesigner.ExplorePOI)},
{"Adventure//POI//Modules//.POIModuleWizard",typeof(Editor_GameDesigner.POIModuleWizard)},
{"Adventure//Discussion//Modules//.CreateDiscussionTree",typeof(Editor_GameDesigner.CreateDiscussionTree)},
{"Core//Animation//.CreateAnimation",typeof(Editor_GameDesigner.CreateAnimation)},
{"Configuration//.CutsceneConfigurationModule",typeof(Editor_GameDesigner.CutsceneConfigurationModule)},
{"Configuration//.DiscussionTreeConfigurationModule",typeof(Editor_GameDesigner.DiscussionTreeConfigurationModule)},
{"Configuration//.ItemConfigurationModule",typeof(Editor_GameDesigner.ItemConfigurationModule)},
{"Configuration//.PointOfInterestConfigurationModule",typeof(Editor_GameDesigner.PointOfInterestConfigurationModule)},
{"Configuration//.AnimationConfigurationModule",typeof(Editor_GameDesigner.AnimationConfigurationModule)},
{"Configuration//.ChunkZonesSceneConfigurationModule",typeof(Editor_GameDesigner.ChunkZonesSceneConfigurationModule)},
{"Configuration//.LevelHierarchyConfigurationModule",typeof(Editor_GameDesigner.LevelHierarchyConfigurationModule)},
{"Configuration//.LevelZonesSceneConfigurationModule",typeof(Editor_GameDesigner.LevelZonesSceneConfigurationModule)},
{"Configuration//.TimelineConfigurationModule",typeof(Editor_GameDesigner.TimelineConfigurationModule)},
{"Configuration//.AIComponentsConfigurationModule",typeof(Editor_GameDesigner.AIComponentsConfigurationModule)},
{"Configuration//.ContextMarkVisualFeedbackConfigurationModule",typeof(Editor_GameDesigner.ContextMarkVisualFeedbackConfigurationModule)},
{"Configuration//.AttractiveObjectConfigurationModule",typeof(Editor_GameDesigner.AttractiveObjectConfigurationModule)},
{"Configuration//.DottedLineConfigurationModule",typeof(Editor_GameDesigner.DottedLineConfigurationModule)},
{"Configuration//.RepelableObjectsConfigurationModule",typeof(Editor_GameDesigner.RepelableObjectsConfigurationModule)},
{"Configuration//.LevelConfigurationModule",typeof(Editor_GameDesigner.LevelConfigurationModule)},
{"Configuration//.PlayerActionConfigurationModule",typeof(Editor_GameDesigner.PlayerActionConfigurationModule)},
{"Configuration//.LaunchProjectileConfigurationModule",typeof(Editor_GameDesigner.LaunchProjectileConfigurationModule)},
{"Configuration//.RangeTypeConfigurationModule",typeof(Editor_GameDesigner.RangeTypeConfigurationModule)},
{"Configuration//.SelectionWheelNodeConfigurationModule",typeof(Editor_GameDesigner.SelectionWheelNodeConfigurationModule)},
{"Configuration//.TargetZoneConfigurationModule",typeof(Editor_GameDesigner.TargetZoneConfigurationModule)},
{"Configuration//.DiscussionTextConfigurationModule",typeof(Editor_GameDesigner.DiscussionTextConfigurationModule)},
{"Configuration//.DisarmObjectConfigurationModule",typeof(Editor_GameDesigner.DisarmObjectConfigurationModule)},
{"Configuration//.PuzzleCutsceneConfigurationModule",typeof(Editor_GameDesigner.PuzzleCutsceneConfigurationModule)},
{"Configuration//.ActionInteractableObjectConfigurationModule",typeof(Editor_GameDesigner.ActionInteractableObjectConfigurationModule)},
{"Configuration//.EditActionInteractableObject",typeof(Editor_GameDesigner.EditActionInteractableObject)},
{"Puzzle//GrabObject//.CreateGrabObject",typeof(Editor_GameDesigner.CreateGrabObject)},
{"Configuration//.GrabObjectConfigurationModule",typeof(Editor_GameDesigner.GrabObjectConfigurationModule)},
{"Puzzle//GrabObject//.EditGrabObject",typeof(Editor_GameDesigner.EditGrabObject)},
{"Configuration//.InputConfigurationModule",typeof(Editor_GameDesigner.InputConfigurationModule)},
{"Configuration//.TutorialStepConfigurationModule",typeof(Editor_GameDesigner.TutorialStepConfigurationModule)},
{"Configuration//.NearPlayerGameOverTriggerConfigurationModule",typeof(Editor_GameDesigner.NearPlayerGameOverTriggerConfigurationModule)},
{"Configuration//.RangeTypeObjectDefinitionConfigurationModule",typeof(Editor_GameDesigner.RangeTypeObjectDefinitionConfigurationModule)},
{"Puzzle//NearPlayerGameOverTrigger//.EditNearPlayerGameOverTrigger",typeof(Editor_GameDesigner.EditNearPlayerGameOverTrigger)},
{"Configuration//.InteractiveObjectTypeDefinitionConfigurationModule",typeof(Editor_GameDesigner.InteractiveObjectTypeDefinitionConfigurationModule)},
};
    }
}
