//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureGame
{
    using UnityEngine;
    using static AnimationConstants;

    [System.Serializable()]
    [UnityEngine.CreateAssetMenu(fileName="PointOfInterestVisualMovementInherentData", menuName="Configuration/AdventureGame/PointOfInterestVisualMovementConfiguration/PointOfInt" +
        "erestVisualMovementInherentData", order=1)]
    public class PointOfInterestVisualMovementInherentData : ScriptableObject
    {
        [Tooltip("The bone that is having visual movmenet")]
        public BipedBone MovingBone = BipedBone.HEAD;
        [Tooltip("This angle is the maximum angle where player actually rotate.")]
        public float RotationAngleLimit = 55f;

        public float SmoothMovementSpeed = 5f;
        [Range(0.0f, 1.0f)]
        [Tooltip("When head exits POI interest, indicates the minimum dot product from current head rotation and target to smooth out." +
            "If calculated dot < SmoothOutMaxDotProductLimit -> no smooth out, head is instantly rotating towards animation rotation.")]
        public float SmoothOutMaxDotProductLimit = 0.4f;
    }
}
