//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureGame
{
    using UnityEngine;
    using ConfigurationEditor;
    using GameConfigurationID;
    using System.Collections.Generic;
    
    
    [System.Serializable()]
    [UnityEngine.CreateAssetMenu(fileName="PointOfInterestVisualMovementConfiguration", menuName="Configuration/AdventureGame/PointOfInterestVisualMovementConfiguration/PointOfInt" +
        "erestVisualMovementConfiguration", order=1)]
    public class PointOfInterestVisualMovementConfiguration : ConfigurationEditor.ConfigurationSerialization<PointOfInterestVisualMovementID, PointOfInterestVisualMovementInherentData>
    {
    }
}
