//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Editor_MainGameCreationWizard;
using GameConfigurationID;
using AdventureGame;
using UnityEditor;

namespace Editor_PointOfInterestDefinitionCreationWizard
{
    [System.Serializable]
    public class PointOfInterestDefinitionConfigurationCreation : CreateableScriptableObjectComponent<PointOfInterestDefinitionInherentData>
    {
        public override void OnGenerationClicked(AbstractCreationWizardEditorProfile editorProfile)
        {
            var editorInfomrationsData = editorProfile.GetModule<EditorInformations>().EditorInformationsData;
            this.CreateAsset(InstancePath.PointOfInterestDefinitionInherentDataPath, editorInfomrationsData.PointOfInterestDefinitionID.ToString() + NameConstants.PointOfInterestDefinitionInherentData, editorProfile);
            this.AddToGameConfiguration(editorInfomrationsData.PointOfInterestDefinitionID, editorInfomrationsData.CommonGameConfigurations.GetConfiguration<PointOfInterestDefinitionConfiguration>(), editorProfile);
        }
    }
}