//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RTPuzzle;
using System;
using UnityEngine;

namespace Editor_GameDesigner
{
    [System.Serializable]
    public class EditNearPlayerGameOverTrigger : EditScriptableObjectModule<NearPlayerGameOverTriggerModule>
    {
        protected override Func<NearPlayerGameOverTriggerModule, ScriptableObject> scriptableObjectResolver
        {
            get
            {
			    return (NearPlayerGameOverTriggerModule NearPlayerGameOverTriggerModule) =>
                {
                    if (this.NearPlayerGameOverTriggerConfiguration.ConfigurationInherentData.ContainsKey(NearPlayerGameOverTriggerModule.NearPlayerGameOverTriggerID))
                    {
                        return this.NearPlayerGameOverTriggerConfiguration.ConfigurationInherentData[NearPlayerGameOverTriggerModule.NearPlayerGameOverTriggerID];
                    }
                    return null;
                };
            }
        }

        private NearPlayerGameOverTriggerConfiguration NearPlayerGameOverTriggerConfiguration;

        public override void OnEnabled()
        {
            this.NearPlayerGameOverTriggerConfiguration = AssetFinder.SafeSingleAssetFind<NearPlayerGameOverTriggerConfiguration>("t:" + typeof(NearPlayerGameOverTriggerConfiguration).Name);
        }
    }
}