//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Editor_MainGameCreationWizard;
using GameConfigurationID;
using RTPuzzle;
using UnityEditor;

namespace Editor_InteractiveObjectTypeDefinitionCreationWizard
{
    [System.Serializable]
    public class InteractiveObjectTypeDefinitionConfigurationCreation : CreateableScriptableObjectComponent<InteractiveObjectTypeDefinitionInherentData>
    {
        public override void OnGenerationClicked(AbstractCreationWizardEditorProfile editorProfile)
        {
            var editorInfomrationsData = editorProfile.GetModule<EditorInformations>().EditorInformationsData;
            var InteractiveObjectTypeDefinitionConfiguration = editorInfomrationsData.CommonGameConfigurations.GetConfiguration<InteractiveObjectTypeDefinitionConfiguration>();
            this.CreateAsset(InstancePath.GetConfigurationDataPath(InteractiveObjectTypeDefinitionConfiguration), editorInfomrationsData.InteractiveObjectTypeDefinitionID.ToString() + "_" +
                this.GetType().BaseType.GetGenericArguments()[0].Name, editorProfile);
            this.AddToGameConfiguration(editorInfomrationsData.InteractiveObjectTypeDefinitionID, InteractiveObjectTypeDefinitionConfiguration, editorProfile);
        }
    }
}