//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Editor_MainGameCreationWizard;
using GameConfigurationID;
using RTPuzzle;
using UnityEditor;

namespace Editor_InteractiveObjectTypeDefinitionCreationWizard
{
    [System.Serializable]
    public class InteractiveObjectTypeDefinitionConfigurationCreation : CreateableScriptableObjectComponent<InteractiveObjectTypeDefinitionInherentData>
    {
        public override void OnGenerationClicked(AbstractCreationWizardEditorProfile editorProfile)
        {
            var editorInfomrationsData = editorProfile.GetModule<EditorInformations>().EditorInformationsData;
            this.CreateAsset(InstancePath.InteractiveObjectTypeDefinitionInherentDataPath, editorInfomrationsData.InteractiveObjectTypeDefinitionID.ToString() + NameConstants.InteractiveObjectTypeDefinitionInherentData, editorProfile);
            this.AddToGameConfiguration(editorInfomrationsData.InteractiveObjectTypeDefinitionID, editorInfomrationsData.CommonGameConfigurations.PuzzleGameConfigurations.InteractiveObjectTypeDefinitionConfiguration, editorProfile);
        }
    }
}