//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RTPuzzle;
using System;
using UnityEngine;

namespace Editor_GameDesigner
{
    [System.Serializable]
    public class EditGrabObject : EditScriptableObjectModule<GrabObjectModule>
    {
        protected override Func<GrabObjectModule, ScriptableObject> scriptableObjectResolver
        {
            get
            {
			    return (GrabObjectModule GrabObjectModule) =>
                {
                    if (this.GrabObjectConfiguration.ConfigurationInherentData.ContainsKey(GrabObjectModule.GrabObjectID))
                    {
                        return this.GrabObjectConfiguration.ConfigurationInherentData[GrabObjectModule.GrabObjectID];
                    }
                    return null;
                };
            }
        }

        private GrabObjectConfiguration GrabObjectConfiguration;

        public override void OnEnabled()
        {
            this.GrabObjectConfiguration = AssetFinder.SafeSingleAssetFind<GrabObjectConfiguration>("t:" + typeof(GrabObjectConfiguration).Name);
        }
    }
}