//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Editor_MainGameCreationWizard;
using GameConfigurationID;
using RTPuzzle;
using UnityEditor;

namespace Editor_AIPatrolGraphCreationWizard
{
    [System.Serializable]
    public class AIPatrolGraphConfigurationCreation : CreateableScriptableObjectComponent<AIPatrolGraphInherentData>
    {
        public override void OnGenerationClicked(AbstractCreationWizardEditorProfile editorProfile)
        {
            var editorInfomrationsData = editorProfile.GetModule<EditorInformations>().EditorInformationsData;
            this.CreateAsset(InstancePath.AIPatrolGraphInherentDataPath, editorInfomrationsData.AIPatrolGraphID.ToString() + NameConstants.AIPatrolGraphInherentData, editorProfile);
            this.AddToGameConfiguration(editorInfomrationsData.AIPatrolGraphID, editorInfomrationsData.CommonGameConfigurations.PuzzleGameConfigurations.AIPatrolGraphConfiguration, editorProfile);
        }
    }
}