//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using RangeObjects;

namespace RTPuzzle
{
    
    
    [UnityEngine.CreateAssetMenu(fileName="PuzzleGameConfiguration", menuName="Configuration/PuzzleGame/PuzzleGameConfiguration", order=1)]
    [System.Serializable()]
    public class PuzzleGameConfiguration : CoreGame.GameConfiguration
    {
        
        public RTPuzzle.LevelConfiguration LevelConfiguration;
        
        public RangeTypeConfiguration RangeTypeConfiguration;
        
        public RTPuzzle.DottedLineConfiguration DottedLineConfiguration;
    }
}
