//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTPuzzle
{
    
    
    [UnityEngine.CreateAssetMenu(fileName="PuzzleGameConfiguration", menuName="Configuration/PuzzleGame/PuzzleGameConfiguration", order=1)]
    [System.Serializable()]
    public class PuzzleGameConfiguration : CoreGame.GameConfiguration
    {
        
        public RTPuzzle.LaunchProjectileConfiguration LaunchProjectileConfiguration;
        
        public RTPuzzle.TargetZoneConfiguration TargetZoneConfiguration;
        
        public RTPuzzle.AttractiveObjectConfiguration AttractiveObjectConfiguration;
        
        public RTPuzzle.LevelConfiguration LevelConfiguration;
        
        public RTPuzzle.SelectionWheelNodeConfiguration SelectionWheelNodeConfiguration;
        
        public RTPuzzle.AIComponentsConfiguration AIComponentsConfiguration;
        
        public RTPuzzle.PlayerActionConfiguration PlayerActionConfiguration;
        
        public RTPuzzle.ContextMarkVisualFeedbackConfiguration ContextMarkVisualFeedbackConfiguration;
        
        public RTPuzzle.RangeTypeConfiguration RangeTypeConfiguration;
        
        public RTPuzzle.DottedLineConfiguration DottedLineConfiguration;
        
        public RTPuzzle.ObjectRepelConfiguration ObjectRepelConfiguration;
        
        public RTPuzzle.DisarmObjectConfiguration DisarmObjectConfiguration;
        
        public RTPuzzle.PuzzleCutsceneConfiguration PuzzleCutsceneConfiguration;
        
        public RTPuzzle.ActionInteractableObjectConfiguration ActionInteractableObjectConfiguration;
        
        public GrabObjectConfiguration GrabObjectConfiguration;
    }
}
