//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



public class GameCreationWizardEditorProfileChoiceTree
{
    
    public static System.Collections.Generic.Dictionary<string, ICreationWizardEditor> configurations = new System.Collections.Generic.Dictionary<string, ICreationWizardEditor>(){
{nameof(Editor_PuzzleLevelCreationWizard.PuzzleLevelCreationWizard),new Editor_PuzzleLevelCreationWizard.PuzzleLevelCreationWizard()},
{nameof(Editor_TargetZoneCreationWizard.TargetZoneCreationWizard),new Editor_TargetZoneCreationWizard.TargetZoneCreationWizard()},
{nameof(Editor_LaunchProjectileCreationWizard.LaunchProjectileCreationWizard),new Editor_LaunchProjectileCreationWizard.LaunchProjectileCreationWizard()},
{nameof(Editor_PlayerActionCreationWizard.PlayerActionCreationWizard),new Editor_PlayerActionCreationWizard.PlayerActionCreationWizard()},
{nameof(Editor_AttractiveObjectCreationWizard.AttractiveObjectCreationWizard),new Editor_AttractiveObjectCreationWizard.AttractiveObjectCreationWizard()},
{nameof(Editor_POICreationWizard.POICreationWizard),new Editor_POICreationWizard.POICreationWizard()},
{nameof(Editor_ObjectRepelCreationWizard.ObjectRepelCreationWizard),new Editor_ObjectRepelCreationWizard.ObjectRepelCreationWizard()},
{nameof(Editor_AdventureBaseLevelCreationWizard.AdventureBaseLevelCreationWizard),new Editor_AdventureBaseLevelCreationWizard.AdventureBaseLevelCreationWizard()},
{nameof(Editor_LevelChunkCreationWizard.LevelChunkCreationWizard),new Editor_LevelChunkCreationWizard.LevelChunkCreationWizard()},
{nameof(Editor_AnimationCreationWizard.AnimationCreationWizard),new Editor_AnimationCreationWizard.AnimationCreationWizard()},
{nameof(Editor_InteractiveObjectCreationWizard.InteractiveObjectCreationWizard),new Editor_InteractiveObjectCreationWizard.InteractiveObjectCreationWizard()},
{nameof(Editor_DiscussionTreeCreationWizard.DiscussionTreeCreationWizard),new Editor_DiscussionTreeCreationWizard.DiscussionTreeCreationWizard()},
{nameof(Editor_DisarmObjectCreationWizard.DisarmObjectCreationWizard),new Editor_DisarmObjectCreationWizard.DisarmObjectCreationWizard()},
{nameof(Editor_ActionInteractableObjectCreationWizard.ActionInteractableObjectCreationWizard),new Editor_ActionInteractableObjectCreationWizard.ActionInteractableObjectCreationWizard()},
{nameof(Editor_GrabObjectCreationWizard.GrabObjectCreationWizard),new Editor_GrabObjectCreationWizard.GrabObjectCreationWizard()},
{nameof(Editor_NearPlayerGameOverTriggerCreationWizard.NearPlayerGameOverTriggerCreationWizard),new Editor_NearPlayerGameOverTriggerCreationWizard.NearPlayerGameOverTriggerCreationWizard()},
{nameof(Editor_InteractiveObjectTypeDefinitionCreationWizard.InteractiveObjectTypeDefinitionCreationWizard),new Editor_InteractiveObjectTypeDefinitionCreationWizard.InteractiveObjectTypeDefinitionCreationWizard()},
{nameof(Editor_RangeTypeObjectDefinitionCreationWizard.RangeTypeObjectDefinitionCreationWizard),new Editor_RangeTypeObjectDefinitionCreationWizard.RangeTypeObjectDefinitionCreationWizard()},
{nameof(Editor_AIObjectTypeDefinitionCreationWizard.AIObjectTypeDefinitionCreationWizard),new Editor_AIObjectTypeDefinitionCreationWizard.AIObjectTypeDefinitionCreationWizard()},
};
}
