//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using GameConfigurationID;
using System;
using System.Collections.Generic;
using UnityEngine;

namespace RTPuzzle
{
    [ModuleMetadata("Interactive")]
    public class AttractiveObjectModuleDefinition : AbstractInteractiveObjectDefinition
    {
        [CustomEnum(ConfigurationType = typeof(AttractiveObjectConfiguration))]
        public AttractiveObjectId AttractiveObjectId;

        public override void CreateObject(Transform parent)
        {
            var puzzlePrefabConfiguration = PuzzleGameSingletonInstances.PuzzleStaticConfigurationContainer.PuzzleStaticConfiguration.PuzzlePrefabConfiguration;
            var attractiveObjectModule = MonoBehaviour.Instantiate(puzzlePrefabConfiguration.BaseAttractiveObjectModule, parent);
            attractiveObjectModule.AttractiveObjectId = this.AttractiveObjectId;
            var RangeTypeObject = MonoBehaviour.Instantiate(puzzlePrefabConfiguration.BaseRangeTypeObject, attractiveObjectModule.transform);
            new RangeTypeObjectDefinitionInherentData()
            {
                RangeDefinitionModules = new Dictionary<Type, ScriptableObject>()
                    {
                        { typeof(RangeTypeDefinition),  new RangeTypeDefinition()
                            {
                                RangeTypeID = RangeTypeID.ATTRACTIVE_OBJECT_ACTIVE,
                                RangeShapeConfiguration = new SphereRangeShapeConfiguration()
                                {
                                    Radius = PuzzleGameSingletonInstances.PuzzleGameConfigurationManager.AttractiveObjectsConfiguration()[attractiveObjectModule.AttractiveObjectId].EffectRange
                                }
                            }
                        },
                        {typeof(RangeObstacleListenerDefinition), new RangeObstacleListenerDefinition() }
                    },
                RangeDefinitionModulesActivation = new Dictionary<Type, bool>()
                    {
                        {typeof(RangeTypeDefinition), true },
                        {typeof(RangeObstacleListenerDefinition), true }
                    }
            }.DefineRangeTypeObject(RangeTypeObject, puzzlePrefabConfiguration);
            RangeTypeObject.RangeTypeObjectDefinitionID = RangeTypeObjectDefinitionID.NONE;
        }
    }
}
