//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventureGame
{
    
    
    [System.Serializable()]
    public class AdventureGameConfigurations
    {
        
        public AdventureGame.ItemConfiguration ItemConfiguration;
        
        public AdventureGame.PointOfInterestConfiguration PointOfInterestConfiguration;
        
        public AdventureGame.CutsceneConfiguration CutsceneConfiguration;
        
        [ReadOnly()]
        public AdventureGame.PointOfInterestDefinitionConfiguration PointOfInterestDefinitionConfiguration;
        
        [ReadOnly()]
        public AdventureGame.PointOfInterestVisualMovementConfiguration PointOfInterestVisualMovementConfiguration;
    }
}
