//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor_MainGameCreationWizard
{
    
    
    [System.Serializable()]
    public class InstancePath
    {
        
        [ReadOnly()]
        public static string LevelBasePath = "Assets/_Scenes";
        
        [ReadOnly()]
        public static string LevelConfigurationDataPath = "Assets/~RTPuzzleGame/Configuration/SubConfiguration/Level/LevelConfigurationData";
        
        [ReadOnly()]
        public static string LevelCompletionDataPath = "Assets/~RTPuzzleGame/Configuration/SubConfiguration/Level/CompletionConfiguration" +
            "/Data";
        
        [ReadOnly()]
        public static string LevelCompletionConditionDataPath = "Assets/~RTPuzzleGame/Configuration/SubConfiguration/Level/CompletionCondition/Dat" +
            "a";
        
        [ReadOnly()]
        public static string PuzzleLevelDynamicsPath = "Assets/~CoreGame/LevelManagement/Prefab";
        
        [ReadOnly()]
        public static string PuzzleLevelHierarchyDataPath = "Assets/~CoreGame/Configuration/SubConfigurations/LevelHierarchyConfiguration/Leve" +
            "lHierarchyConfigurationData";
        
        [ReadOnly()]
        public static string LevelZoneSceneConfigurationDataPath = "Assets/~CoreGame/Configuration/SubConfigurations/LevelZonesSceneConfiguration/Lev" +
            "elZonesSceneConfigurationData";
        
        [ReadOnly()]
        public static string LevelZoneChunkSceneConfigurationDataPath = "Assets/~CoreGame/Configuration/SubConfigurations/ChunkZonesSceneConfiguration/Chu" +
            "nkZonesSceneConfigurationData";
        
        [ReadOnly()]
        public static string LevelChunkBaseLevelPrefabPath = "Assets/~CoreGame/LevelManagement/Prefab";
        
        [ReadOnly()]
        public static string AIPrefabPaths = "Assets/~RTPuzzleGame/AI/Prefabs";
        
        [ReadOnly()]
        public static string AIBehaviorConfigurationPath = "Assets/~RTPuzzleGame/Configuration/SubConfiguration/AIComponentsConfiguration/Con" +
            "figuration";
        
        [ReadOnly()]
        public static string TargetZoneConfigurationDataPath = "Assets/~RTPuzzleGame/Configuration/SubConfiguration/TargetZonesConfiguration/Data" +
            "";
        
        [ReadOnly()]
        public static string TargetZonePrefabPath = "Assets/~RTPuzzleGame/TargetZone/Prefab";
        
        [ReadOnly()]
        public static string ProjectileInherentDataPath = "Assets/~RTPuzzleGame/Configuration/SubConfiguration/LaunchProjectileConfiguration" +
            "/Data";
        
        [ReadOnly()]
        public static string ProjectilePrefabPath = "Assets/~RTPuzzleGame/PlayerAction/ActionExecution/Scripts/LaunchProjectileAction/" +
            "Prefab";
        
        [ReadOnly()]
        public static string DisarmObjectInherentDatapath = "Assets/~RTPuzzleGame/Configuration/SubConfiguration/DisarmObjectConfiguration/Dat" +
            "a";
        
        [ReadOnly()]
        public static string NearPlayerGameOverTriggerInherentDataPath = "Assets/~RTPuzzleGame/Configuration/SubConfiguration/NearPlayerGameOverTriggerConf" +
            "iguration/Data";
        
        [ReadOnly()]
        public static string ActionInteractableObjectInherentDatapath = "Assets/~RTPuzzleGame/Configuration/SubConfiguration/ActionInteractableObjectConfi" +
            "guration/Data";
        
        [ReadOnly()]
        public static string PlayerActionInherentDataPath = "Assets/~RTPuzzleGame/Configuration/SubConfiguration/PlayerActionConfiguration/Pla" +
            "yerActionInherentData/Data";
        
        [ReadOnly()]
        public static string POIPrefabPath = "Assets/~AdventureGame/PointOfInterest/ScenePOI/Items";
        
        [ReadOnly()]
        public static string POIInherentDataPath = "Assets/~AdventureGame/Configuration/SubConfiguration/PointOfInterestConfiguration" +
            "/Data";
        
        [ReadOnly()]
        public static string AttractiveObjectInherantDataPath = "Assets/~RTPuzzleGame/Configuration/SubConfiguration/AttractiveObjectConfiguration" +
            "/AttractiveObjectInherentConfigurationData";
        
        [ReadOnly()]
        public static string RepelableObjectInherentDataPath = "Assets/~RTPuzzleGame/Configuration/SubConfiguration/InteractiveObjects/RepelableO" +
            "bjectsConfiguration/RepelableObjectsConfigurationData";
        
        [ReadOnly()]
        public static string RepelableObjectPrefabPath = "Assets/~RTPuzzleGame/PlayerAction/PlayerActionInteractionBehavior/Repel/Prefabs";
        
        [ReadOnly()]
        public static string AnimationConfigurationDataPath = "Assets/~CoreGame/Configuration/SubConfigurations/AnimationConfiguration/Animation" +
            "ConfigurationData";
        
        [ReadOnly()]
        public static string InteractiveObjectPrefabPath = "Assets/~RTPuzzleGame/InteractiveObject/Prefabs";
        
        [ReadOnly()]
        public static string DiscussionTreePath = "Assets/Editor/Configuration/AdventureGame/DiscussionConfiguration";
        
        [ReadOnly()]
        public static string CutsceneGraphPath = "Assets/~AdventureGame/Configuration/SubConfiguration/CutsceneConfiguration/Cutsce" +
            "neConfigurationData";
        
        [ReadOnly()]
        public static string InteractiveTestInherentDataPath = "Assets/~RTPuzzleGame/Configuration/SubConfiguration/InteractiveTestConfiguration/" +
            "Data";
        
        [ReadOnly()]
        public static string GrabObjectInherentDataPath = "Assets/~RTPuzzleGame/Configuration/SubConfiguration/GrabObjectConfiguration/Data";
        
        [ReadOnly()]
        public static string CreationWizardTestInherentDataPath = "Assets/~RTPuzzleGame/Configuration/SubConfiguration/CreationWizardTestConfigurati" +
            "on/Data";
        
        [ReadOnly()]
        public static string InteractiveObjectTypeDefinitionConfigurationInherentDataPath = "Assets/~RTPuzzleGame/Configuration/SubConfiguration/InteractiveObjectTypeDefiniti" +
            "onConfigurationConfiguration/Data";
        
        [ReadOnly()]
        public static string InteractiveObjectTypeDefinitionInherentDataPath = "Assets/~RTPuzzleGame/Configuration/SubConfiguration/InteractiveObjectTypeDefiniti" +
            "onConfiguration/Data";
        
        [ReadOnly()]
        public static string RangeTypeObjectDefinitionInherentDataPath = "Assets/~RTPuzzleGame/Configuration/SubConfiguration/RangeTypeObjectDefinitionConf" +
            "iguration/Data";
        
        [ReadOnly()]
        public static string AIObjectTypeDefinitionInherentDataPath = "Assets/~RTPuzzleGame/Configuration/SubConfiguration/AIObjectTypeDefinitionConfigu" +
            "ration/Data";
        
        [ReadOnly()]
        public static string PuzzleCutsceneInherentDataPath = "Assets/~RTPuzzleGame/Configuration/SubConfiguration/PuzzleCutsceneConfiguration/D" +
            "ata";
        
        [ReadOnly()]
        public static string AdventureGenTestInherentDataPath = "Assets/~AdventureGame/Configuration/SubConfiguration/AdventureGenTestConfiguratio" +
            "n/Data";
        
        [ReadOnly()]
        public static string AdventureGenerationTestInherentDataPath = "Assets/~AdventureGame/Configuration/SubConfiguration/AdventureGenerationTestConfi" +
            "guration/Data";
        
        [ReadOnly()]
        public static string PointOfInterestDefinitionInherentDataPath = "Assets/~AdventureGame/Configuration/SubConfiguration/PointOfInterestDefinitionCon" +
            "figuration/Data";
        
        [ReadOnly()]
        public static string PointOfInterestVisualMovementInherentDataPath = "Assets/~AdventureGame/Configuration/SubConfiguration/PointOfInterestVisualMovemen" +
            "tConfiguration/Data";
    }
}
