//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;

namespace Editor_MainGameCreationWizard
{


    [System.Serializable()]
    public class InstancePath
    {
        #region RTPuzzle
        public static string GetConfigurationDataPath(ScriptableObject configurationAsset)
        {
            return AssetHelper.GetAssetPath(configurationAsset, false) + "/Data";
        }

        [ReadOnly()]
        public static string LevelCompletionConditionDataPath = "Assets/~RTPuzzleGame/__Features/LevelCompletion/Configuration/CompletionCondition/Data";
        #endregion

        [ReadOnly()]
        public static string LevelBasePath = "Assets/_Scenes";

        [ReadOnly()]
        public static string PuzzleLevelDynamicsPath = "Assets/~CoreGame/LevelManagement/Prefab";

        [ReadOnly()]
        public static string PuzzleLevelHierarchyDataPath = "Assets/~CoreGame/Configuration/SubConfigurations/LevelHierarchyConfiguration/Data";

        [ReadOnly()]
        public static string LevelZoneSceneConfigurationDataPath = "Assets/~CoreGame/Configuration/SubConfigurations/LevelZonesSceneConfiguration/Data";

        [ReadOnly()]
        public static string LevelZoneChunkSceneConfigurationDataPath = "Assets/~CoreGame/Configuration/SubConfigurations/ChunkZonesSceneConfiguration/Data";

        [ReadOnly()]
        public static string LevelChunkBaseLevelPrefabPath = "Assets/~CoreGame/LevelManagement/Prefab";

    }
}
