//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;

namespace Editor_MainGameCreationWizard
{


    [System.Serializable()]
    public class InstancePath
    {
        #region RTPuzzle
        public static string GetConfigurationDataPath(ScriptableObject configurationAsset)
        {
            return AssetHelper.GetAssetPath(configurationAsset, false) + "/Data";
        }

        [ReadOnly()]
        public static string LevelCompletionDataPath = "Assets/~RTPuzzleGame/Configuration/SubConfiguration/Level/CompletionConfiguration" +
            "/Data";

        [ReadOnly()]
        public static string LevelCompletionConditionDataPath = "Assets/~RTPuzzleGame/Configuration/SubConfiguration/Level/CompletionCondition/Dat" +
            "a";
        #endregion



        [ReadOnly()]
        public static string LevelBasePath = "Assets/_Scenes";

        [ReadOnly()]
        public static string PuzzleLevelDynamicsPath = "Assets/~CoreGame/LevelManagement/Prefab";

        [ReadOnly()]
        public static string PuzzleLevelHierarchyDataPath = "Assets/~CoreGame/Configuration/SubConfigurations/LevelHierarchyConfiguration/Leve" +
            "lHierarchyConfigurationData";

        [ReadOnly()]
        public static string LevelZoneSceneConfigurationDataPath = "Assets/~CoreGame/Configuration/SubConfigurations/LevelZonesSceneConfiguration/Lev" +
            "elZonesSceneConfigurationData";

        [ReadOnly()]
        public static string LevelZoneChunkSceneConfigurationDataPath = "Assets/~CoreGame/Configuration/SubConfigurations/ChunkZonesSceneConfiguration/Chu" +
            "nkZonesSceneConfigurationData";

        [ReadOnly()]
        public static string LevelChunkBaseLevelPrefabPath = "Assets/~CoreGame/LevelManagement/Prefab";





        [ReadOnly()]
        public static string POIInherentDataPath = "Assets/~AdventureGame/Configuration/SubConfiguration/PointOfInterestConfiguration" +
            "/Data";


        [ReadOnly()]
        public static string AnimationConfigurationDataPath = "Assets/~CoreGame/Configuration/SubConfigurations/AnimationConfiguration/Animation" +
            "ConfigurationData";


        [ReadOnly()]
        public static string DiscussionTreePath = "Assets/Editor/Configuration/AdventureGame/DiscussionConfiguration";

        [ReadOnly()]
        public static string CutsceneGraphPath = "Assets/~AdventureGame/Configuration/SubConfiguration/CutsceneConfiguration/Cutsce" +
            "neConfigurationData";




        [ReadOnly()]
        public static string AdventureGenTestInherentDataPath = "Assets/~AdventureGame/Configuration/SubConfiguration/AdventureGenTestConfiguratio" +
            "n/Data";

        [ReadOnly()]
        public static string AdventureGenerationTestInherentDataPath = "Assets/~AdventureGame/Configuration/SubConfiguration/AdventureGenerationTestConfi" +
            "guration/Data";

        [ReadOnly()]
        public static string PointOfInterestDefinitionInherentDataPath = "Assets/~AdventureGame/Configuration/SubConfiguration/PointOfInterestDefinitionCon" +
            "figuration/Data";

        [ReadOnly()]
        public static string PointOfInterestVisualMovementInherentDataPath = "Assets/~AdventureGame/Configuration/SubConfiguration/PointOfInterestVisualMovemen" +
            "tConfiguration/Data";

        [ReadOnly()]
        public static string PointOfInterestModuleTestInherentDataPath = "Assets/~AdventureGame/Configuration/SubConfiguration/PointOfInterestModuleTestCon" +
            "figuration/Data";


    }
}
