//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor_MainGameCreationWizard
{
    
    
    [System.Serializable()]
    public class PuzzleGameConfigurations
    {
        
        [ReadOnly()]
        public RTPuzzle.LevelConfiguration LevelConfiguration;
        
        [ReadOnly()]
        public CoreGame.LevelZonesSceneConfiguration LevelZonesSceneConfiguration;
        
        [ReadOnly()]
        public CoreGame.LevelHierarchyConfiguration LevelHierarchyConfiguration;
        
        [ReadOnly()]
        public CoreGame.ChunkZonesSceneConfiguration ChunkZonesSceneConfiguration;
        
        [ReadOnly()]
        public RTPuzzle.AIComponentsConfiguration AIComponentsConfiguration;
        
        [ReadOnly()]
        public RTPuzzle.TargetZoneConfiguration TargetZoneConfiguration;
        
        [ReadOnly()]
        public RTPuzzle.LaunchProjectileConfiguration LaunchProjectileConfiguration;
        
        [ReadOnly()]
        public RTPuzzle.PlayerActionConfiguration PlayerActionConfiguration;
        
        [ReadOnly()]
        public RTPuzzle.AttractiveObjectConfiguration AttractiveObjectConfiguration;
        
        [ReadOnly()]
        public RTPuzzle.ObjectRepelConfiguration ObjectRepelConfiguration;
        
        [ReadOnly()]
        public RTPuzzle.DisarmObjectConfiguration DisarmObjectConfiguration;
        
        [ReadOnly()]
        public RTPuzzle.ActionInteractableObjectConfiguration ActionInteractableObjectConfiguration;
        
        [ReadOnly()]
        public RTPuzzle.GrabObjectConfiguration GrabObjectConfiguration;

        [ReadOnly()]
        public RTPuzzle.NearPlayerGameOverTriggerConfiguration NearPlayerGameOverTriggerConfiguration;
    }
}
