//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor_MainGameCreationWizard
{
    using RTPuzzle;
    
    
    [System.Serializable()]
    public class PuzzleAICommonPrefabs
    {
        
        [ReadOnly()]
        public RTPuzzle.NPCAIManager AIBasePrefab;
        
        [ReadOnly()]
        public RTPuzzle.AIAttractiveObjectLooseManager AIAttractiveObjectLooseManager;
        
        [ReadOnly()]
        public RTPuzzle.AIAttractiveObjectPersistantManager AIAttractiveObjectPersistantManager;
        
        [ReadOnly()]
        public RTPuzzle.AIEscapeWithoutTriggerManager AIEscapeWithoutTriggerManager;
        
        [ReadOnly()]
        public RTPuzzle.AIFearStunManager AIFearStunManager;
        
        [ReadOnly()]
        public RTPuzzle.AIRandomPatrolComponentMananger AIRandomPatrolComponentMananger;
        
        [ReadOnly()]
        public RTPuzzle.AIScriptedPatrolComponentManager AIScriptedPatrolComponentManager;
        
        [ReadOnly()]
        public RTPuzzle.AIPlayerEscapeManager AIPlayerEscapeManager;
        
        [ReadOnly()]
        public RTPuzzle.AIProjectileWithCollisionEscapeManager AIProjectileWithCollisionEscapeManager;
        
        [ReadOnly()]
        public RTPuzzle.AITargetZoneEscapeManager AITargetZoneEscapeManager;
        
        [ReadOnly()]
        public RTPuzzle.ObjectSightModule AISightVision;
        
        [ReadOnly()]
        public RTPuzzle.AIMoveTowardPlayerManager AIMoveTowardPlayerManager;
        
        [ReadOnly()]
        public RTPuzzle.AIDisarmObjectManager AIDisarmObjectManager;
    }
}
