//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTPuzzle
{
    
    
    [System.Serializable()]
    public class PuzzleInteractiveObjectModulePrefabs
    {
        
        [ReadOnly()]
        public RTPuzzle.ModelObjectModule BaseModelObjectModule;
        
        [ReadOnly()]
        public RTPuzzle.ObjectRepelModule BaseObjectRepelModule;
        
        [ReadOnly()]
        public RTPuzzle.AttractiveObjectModule BaseAttractiveObjectModule;
        
        [ReadOnly()]
        public RTPuzzle.TargetZoneModule BaseTargetZoneModule;
        
        [ReadOnly()]
        public RTPuzzle.LevelCompletionTriggerModule BaseLevelCompletionTriggerModule;
        
        [ReadOnly()]
        public RTPuzzle.LaunchProjectileModule BaseLaunchProjectileModule;
        
        [ReadOnly()]
        public RTPuzzle.DisarmObjectModule BaseDisarmObjectModule;
        
        [ReadOnly()]
        public RTPuzzle.ActionInteractableObjectModule BaseActionInteractableObjectModule;
        
        [ReadOnly()]
        public GrabObjectModule BaseGrabObjectModule;
    }
}
