//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Editor_MainGameCreationWizard
{
    using RTPuzzle;
    
    
    [System.Serializable()]
    public class PuzzleAICommonPrefabs
    {
        
        [ReadOnly()]
        public NPCAIManager AIBasePrefab;
        
        [ReadOnly()]
        public AIAttractiveObjectLooseManager AIAttractiveObjectLooseManager;
        
        [ReadOnly()]
        public AIAttractiveObjectPersistantManager AIAttractiveObjectPersistantManager;
        
        [ReadOnly()]
        public AIEscapeWithoutTriggerManager AIEscapeWithoutTriggerManager;
        
        [ReadOnly()]
        public AIFearStunManager AIFearStunManager;
        
        [ReadOnly()]
        public AIRandomPatrolComponentMananger AIRandomPatrolComponentMananger;
        
        [ReadOnly()]
        public AIScriptedPatrolComponentManager AIScriptedPatrolComponentManager;
        
        [ReadOnly()]
        public AIPlayerEscapeManager AIPlayerEscapeManager;
        
        [ReadOnly()]
        public AIProjectileWithCollisionEscapeManager AIProjectileWithCollisionEscapeManager;
        
        [ReadOnly()]
        public AITargetZoneEscapeManager AITargetZoneEscapeManager;
        
        [ReadOnly()]
        public AISightVision AISightVision;
        
        [ReadOnly()]
        public AIMoveTowardPlayerManager AIMoveTowardPlayerManager;
    }
}
